import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard', tasks: 'Tasks', weekly: 'Weekly', today: 'Today',
    emailSync: 'Email Sync', addTask: '+ Add Task', profile: 'Profile', logout: 'Logout',
    changePassword: 'Change Password', welcome: 'Welcome', yourTasks: 'Your Tasks',
    noTasks: 'No tasks yet', addNewTask: 'Add New Task', editTask: 'Edit Task',
    title: 'Title', description: 'Description', dueDate: 'Due Date', priority: 'Priority',
    course: 'Course', low: 'Low', medium: 'Medium', high: 'High',
    save: 'Save', cancel: 'Cancel', delete: 'Delete', complete: 'Complete',
    settings: 'Settings', language: 'Language', aiAssistant: 'AI Study Assistant',
    connectMicrosoft: 'Sign in with Microsoft', syncNow: 'Sync Now',
    connected: 'Connected', disconnected: 'Disconnected',
    taskAdded: 'Task added successfully!', failedToAdd: 'Failed to add task: ',
    taskUpdated: 'Task updated successfully!', failedToUpdate: 'Failed to update task: ',
    taskDeleted: 'Task deleted successfully!', failedToDelete: 'Failed to delete task: ',
    failedToUpdateTask: 'Failed to update task: ',
    deleteConfirm: 'Are you sure you want to delete this task?',
    loadingTasks: 'Loading tasks...',
    email: 'Email', password: 'Password', name: 'Name',
    login: 'Login', register: 'Register', dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?', signUp: 'Sign Up', signIn: 'Sign In',
    welcomeBack: 'Welcome Back', createAccount: 'Create Account',
    manageTasks: 'Manage your tasks and stay organized',
    notifications: 'Notifications', noNotifications: 'No notifications',
    markAllRead: 'Mark all as read', noDueDate: 'No due date',
    overdue: 'Overdue', dueToday: 'Due Today', dueTomorrow: 'Due Tomorrow',
    upcoming: 'Upcoming', completed: 'Completed', pending: 'Pending',
    all: 'All', filterBy: 'Filter by', sortBy: 'Sort by', search: 'Search',
    duration: 'Duration', minutes: 'minutes', hours: 'hours',
    taskDetails: 'Task Details', noDescription: 'No description',
    edit: 'Edit', close: 'Close', select: 'Select', update: 'Update', 
    smartEmailSync: 'Smart Email Sync', importAssignments: 'Automatically import assignments from your university email',
    howItWorks: 'How It Works', signInMicrosoft: 'Click "Sign in with Microsoft" to connect your university account',
    grantPermission: 'Grant permission to read your emails (Planora only reads subjects)',
    clickSync: 'Click "Sync Now" to import your recent assignments',
    automaticSync: 'Automatic sync runs every 15 minutes',
    taggedAs: 'Tasks are tagged as "Assignment" or "Announcement"',
    accountConnected: 'Account connected successfully!', disconnect: 'Disconnect',
    tokenActive: 'Active', tokenNeedsRefresh: 'Needs refresh',
    syncing: 'Syncing...', syncComplete: 'Sync completed! New tasks added to dashboard.',
    syncError: 'Sync error: ',
    errorConnecting: 'Error connecting: ', token: 'Token',
    todaysPlan: "Today's Plan", recommendedForYou: 'Recommended for you',
    basedOnPriority: 'Based on your task priorities and deadlines',
    noTasksToday: 'No tasks due today. Enjoy your free time!',
    noTasksMatch: 'No tasks match your search',
    weeklyOverview: 'Weekly Overview', workloadDistribution: 'Workload Distribution',
    noTasksThisWeek: 'No tasks scheduled for this week',
    previousWeek: 'Previous Week', nextWeek: 'Next Week', thisWeek: 'This Week',
    monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday',
    friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
    loading: 'Loading...', unknown: 'Unknown', loadingAccount: 'Loading...',
    accountInfo: 'Account Information', emailAddress: 'Email Address',
    newPassword: 'New Password', enterNewPassword: 'Enter new password',
    error: 'Error', success: 'Success', pleaseWait: 'Please wait...',
    addFirstTask: 'Add your first task!', noTasksYet: 'No tasks yet. Add your first task!',
    viewAll: 'View All', markComplete: 'Mark Complete', markIncomplete: 'Mark Incomplete',
    todayAt: 'Today at', tomorrowAt: 'Tomorrow at',
    focusMode: 'Focus Mode', selectDuration: 'Select Duration', min: 'min',
    startFocus: 'Start Focus', pause: 'Pause', resume: 'Resume', reset: 'Reset',
    ready: 'Ready', focusing: 'Focusing', paused: 'Paused',
    sessionsToday: 'Sessions Today', enableNotifications: 'Enable notifications for reminders',
    enable: 'Enable', set: 'Set',     focusComplete: 'Great job! Take a short break.',
    backToWork: "Welcome back! Let's get back to focused work.",
    aiAccounts: 'AI Accounts', aiSettingsDesc: 'Connect your AI provider accounts to use different AI models in the chatbot.',
    aiPrivacyNote: 'Planora does not store your credentials. Authentication is handled securely by the providers.',
    enterApiKey: 'Enter API Key',
  },
  es: {
    dashboard: 'Panel', tasks: 'Tareas', weekly: 'Semanal', today: 'Hoy',
    emailSync: 'Sincronizar Email', addTask: '+ Agregar Tarea', profile: 'Perfil',
    logout: 'Cerrar Sesión', changePassword: 'Cambiar Contraseña', welcome: 'Bienvenido',
    yourTasks: 'Tus Tareas', noTasks: 'Sin tareas aún', addNewTask: 'Agregar Nueva Tarea',
    editTask: 'Editar Tarea', title: 'Título', description: 'Descripción',
    dueDate: 'Fecha de Vencimiento', priority: 'Prioridad', course: 'Curso',
    low: 'Baja', medium: 'Media', high: 'Alta', save: 'Guardar', cancel: 'Cancelar',
    delete: 'Eliminar', complete: 'Completar', settings: 'Configuración',
    language: 'Idioma', aiAssistant: 'Asistente de Estudio IA',
    connectMicrosoft: 'Iniciar sesión con Microsoft', syncNow: 'Sincronizar Ahora',
    connected: 'Conectado', disconnected: 'Desconectado',
  },
  fr: {
    dashboard: 'Tableau de Bord', tasks: 'Tâches', weekly: 'Hebdomadaire', today: "Aujourd'hui",
    emailSync: 'Sync Email', addTask: '+ Ajouter Tâche', profile: 'Profil',
    logout: 'Déconnexion', changePassword: 'Changer le Mot de Passe', welcome: 'Bienvenue',
    yourTasks: 'Vos Tâches', noTasks: 'Pas encore de tâches', addNewTask: 'Ajouter Nouvelle Tâche',
    editTask: 'Modifier Tâche', title: 'Titre', description: 'Description',
    dueDate: "Date d'échéance", priority: 'Priorité', course: 'Cours',
    low: 'Basse', medium: 'Moyenne', high: 'Haute', save: 'Enregistrer', cancel: 'Annuler',
    delete: 'Supprimer', complete: 'Terminer', settings: 'Paramètres',
    language: 'Langue', aiAssistant: 'Assistant Étude IA',
    connectMicrosoft: 'Se connecter avec Microsoft', syncNow: 'Synchroniser',
    connected: 'Connecté', disconnected: 'Déconnecté',
  },
  ar: {
    dashboard: 'لوحة التحكم', tasks: 'المهام', weekly: 'أسبوعي', today: 'اليوم',
    emailSync: 'مزامنة البريد', addTask: '+ إضافة مهمة', profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج', changePassword: 'تغيير كلمة المرور', welcome: 'مرحبا',
    yourTasks: 'مهامك', noTasks: 'لا توجد مهام بعد', addNewTask: 'إضافة مهمة جديدة',
    editTask: 'تعديل المهمة', title: 'العنوان', description: 'الوصف',
    dueDate: 'تاريخ الاستحقاق', priority: 'الأولوية', course: 'المقرر',
    low: 'منخفضة', medium: 'متوسطة', high: 'عالية', save: 'حفظ', cancel: 'إلغاء',
    delete: 'حذف', complete: 'إكمال', settings: 'الإعدادات',
    language: 'اللغة', aiAssistant: 'مساعد الدراسة الذكي',
    connectMicrosoft: 'تسجيل الدخول عبر Microsoft', syncNow: 'مزامنة الآن',
    connected: 'متصل', disconnected: 'غير متصل',
  },
  de: {
    dashboard: 'Übersicht', tasks: 'Aufgaben', weekly: 'Woche', today: 'Heute',
    emailSync: 'E-Mail Sync', addTask: '+ Aufgabe hinzufügen', profile: 'Profil',
    logout: 'Abmelden', changePassword: 'Passwort ändern', welcome: 'Willkommen',
    yourTasks: 'Ihre Aufgaben', noTasks: 'Noch keine Aufgaben', addNewTask: 'Neue Aufgabe hinzufügen',
    editTask: 'Aufgabe bearbeiten', title: 'Titel', description: 'Beschreibung',
    dueDate: 'Fälligkeitsdatum', priority: 'Priorität', course: 'Kurs',
    low: 'Niedrig', medium: 'Mittel', high: 'Hoch', save: 'Speichern', cancel: 'Abbrechen',
    delete: 'Löschen', complete: 'Abschließen', settings: 'Einstellungen',
    language: 'Sprache', aiAssistant: 'KI Lernassistent',
    connectMicrosoft: 'Mit Microsoft anmelden', syncNow: 'Jetzt synchronisieren',
    connected: 'Verbunden', disconnected: 'Getrennt',
  },
  zh: {
    dashboard: '仪表板', tasks: '任务', weekly: '每周', today: '今天',
    emailSync: '邮件同步', addTask: '+ 添加任务', profile: '个人资料',
    logout: '退出登录', changePassword: '更改密码', welcome: '欢迎',
    yourTasks: '您的任务', noTasks: '暂无任务', addNewTask: '添加新任务',
    editTask: '编辑任务', title: '标题', description: '描述',
    dueDate: '截止日期', priority: '优先级', course: '课程',
    low: '低', medium: '中', high: '高', save: '保存', cancel: '取消',
    delete: '删除', complete: '完成', settings: '设置',
    language: '语言', aiAssistant: 'AI学习助手',
    connectMicrosoft: '使用Microsoft登录', syncNow: '立即同步',
    connected: '已连接', disconnected: '未连接',
  },
  hi: {
    dashboard: 'डैशबोर्ड', tasks: 'कार्य', weekly: 'साप्ताहिक', today: 'आज',
    emailSync: 'ईमेल सिंक', addTask: '+ कार्य जोड़ें', profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट', changePassword: 'पासवर्ड बदलें', welcome: 'स्वागत है',
    yourTasks: 'आपके कार्य', noTasks: 'अभी तक कोई कार्य नहीं', addNewTask: 'नया कार्य जोड़ें',
    editTask: 'कार्य संपादित करें', title: 'शीर्षक', description: 'विवरण',
    dueDate: 'नियत तारीख', priority: 'प्राथमिकता', course: 'कोर्स',
    low: 'कम', medium: 'मध्यम', high: 'उच्च', save: 'सहेजें', cancel: 'रद्द करें',
    delete: 'हटाएं', complete: 'पूर्ण', settings: 'सेटिंग्स',
    language: 'भाषा', aiAssistant: 'AI अध्ययन सहायक',
    connectMicrosoft: 'Microsoft से कनेक्ट करें', syncNow: 'अभी सिंक करें',
    connected: 'कनेक्टेड', disconnected: 'डिस्कनेक्टेड',
  },
  ta: {
    dashboard: 'டैஷ்போர்டு', tasks: 'பணிகள்', weekly: 'வாராந்திர', today: 'இன்று',
    emailSync: 'மின்னஞ்சல் ஒத்திசைவு', addTask: '+ பணி சேர்', profile: 'சுயவிவரம்',
    logout: 'வெளியேறு', changePassword: 'கடவுச்சொல் மாற்று', welcome: 'வரவேற்கிறோம்',
    yourTasks: 'உங்கள் பணிகள்', noTasks: 'பணிகள் இல்லை', addNewTask: 'புதிய பணி சேர்',
    editTask: 'பணி திருத்து', title: 'தலைப்பு', description: 'விளக்கம்',
    dueDate: 'இறுதி தேதி', priority: 'முன்னுரிமை', course: 'பாடம்',
    low: 'குறைந்த', medium: 'நடுத்தர', high: 'உயர்ந்த', save: 'சேமி', cancel: 'ரத்து',
    delete: 'நீக்கு', complete: 'முடித்தார்', settings: 'அமைப்புகள்',
    language: 'மொழி', aiAssistant: 'AI கற்றல் உதவியாளர்',
    connectMicrosoft: 'Microsoft உடன் உள்நுழைக', syncNow: 'இப்போது ஒத்திசைக்க',
    connected: 'இணைக்கப்பட்டது', disconnected: 'இணைக்கப்படவில்லை',
  },
  te: {
    dashboard: 'डैशबोर्ड', tasks: 'కార్యాలు', weekly: 'वार्षिक', today: 'ఈరోజు',
    emailSync: 'ఇమెయిల్ sync', addTask: '+ కార్యం చేర్చు', profile: 'ప్రofil',
    logout: 'లాగ్ out', changePassword: 'password मिड', welcome: 'स्वागत',
    yourTasks: 'మీ कार्य', noTasks: 'कार्य लागू', addNewTask: 'क نو कार्य',
    editTask: 'कार्य संपादित', title: 'शीर्षक', description: 'विवरण',
    dueDate: 'नियत तारीख', priority: 'प्राथमिकता', course: 'कोर्स',
    low: 'कम', medium: 'मध्यम', high: 'उच्च', save: 'save', cancel: 'रद्द',
    delete: 'हटाएं', complete: 'पूर्ण', settings: 'सेटिंग्स',
    language: 'भाषा', aiAssistant: 'AI learning assist',
    connectMicrosoft: 'Microsoft login', syncNow: 'sync now',
    connected: 'connected', disconnected: 'disconnected',
  },
  mr: {
    dashboard: 'डॅशबोर्ड', tasks: 'कार्ये', weekly: 'साप्ताहिक', today: 'आज',
    emailSync: 'ईमेल सिंक', addTask: '+ कार्य जोडा', profile: 'प्रोफाइल',
    logout: 'लॉग आउट', changePassword: 'पासवर्ड बदला', welcome: 'स्वागत आहे',
    yourTasks: 'तुमची कार्ये', noTasks: 'अद्याप कार्य नाहीत', addNewTask: 'नवीन कार्य जोडा',
    editTask: 'कार्य संपादित करा', title: 'शीर्षक', description: 'वर्णन',
    dueDate: 'शेवटची तारीख', priority: 'प्राधान्य', course: 'कोर्स',
    low: 'कम', medium: 'मध्यम', high: 'उच्च', save: 'जतन करा', cancel: 'रद्द करा',
    delete: 'हटवा', complete: 'पूर्ण', settings: 'सेटिंग्ज',
    language: 'भाषा', aiAssistant: 'AI अभ्यास सहायक',
    connectMicrosoft: 'Microsoft ने लॉगिन करा', syncNow: 'आता सिंक करा',
    connected: 'जोडलेले', disconnected: 'डिस्कनेक्टेड',
  },
  gu: {
    dashboard: 'ડૅશબોર્ડ', tasks: 'કામ', weekly: 'સાપ્તાહિક', today: 'આજ',
    emailSync: 'ઈમેલ સિંક', addTask: '+ કામ ઉમેરો', profile: 'પ્રોફાઈલ',
    logout: 'લોગ આઉટ', changePassword: 'પાસવર્ડ બદલો', welcome: 'સ્વાગત છે',
    yourTasks: 'તમારા કામ', noTasks: 'હજુ કોઈ કામ નથી', addNewTask: 'નવું કામ ઉમેરો',
    editTask: 'કામ સંપાદિત કરો', title: 'શીર્ષક', description: 'વર્ણન',
    dueDate: 'અંતિમ તારીખ', priority: 'પ્રાથમિકતા', course: 'અભ્યાસ',
    low: 'નીચું', medium: 'મધ્યમ', high: 'ઉચ્ચ', save: 'સંગ્રહ', cancel: 'રદ',
    delete: 'હટાવો', complete: 'પૂર્ણ', settings: 'સેટિંગ્સ',
    language: 'ભાષા', aiAssistant: 'AI અભ્યાસ સહાયક',
    connectMicrosoft: 'Microsoft થી લોગિન', syncNow: 'હવે સિંક',
    connected: 'જોડાયેલ', disconnected: 'ડિસ્કનેક્ટેડ',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', tasks: 'ಕಾರ್ಯಗಳು', weekly: 'ವಾರದ', today: 'ಇಂದು',
    emailSync: 'ಇಮೇಲ್ ಸಿಂಕ್', addTask: '+ ಕಾರ್ಯ ಸೇರಿಸಿ', profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್‌ಔಟ್', changePassword: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ', welcome: 'ಸ್ವಾಗತ',
    yourTasks: 'ನಿಮ್ಮ ಕಾರ್ಯಗಳು', noTasks: 'ಇನ್ನೂ ಕಾರ್ಯಗಳಿಲ್ಲ', addNewTask: 'ಹೊಸ ಕಾರ್ಯ ಸೇರಿಸಿ',
    editTask: 'ಕಾರ್ಯ ಸಂಪಾದಿಸಿ', title: 'ಶೀರ್ಷಿಕೆ', description: 'ವಿವರಣೆ',
    dueDate: 'ಗಡುವು', priority: 'ಆದ್ಯತೆ', course: 'ಕೋರ್ಸ್',
    low: 'ಕಡಿಮೆ', medium: 'ಮಧ್ಯಮ', high: 'ಎತ್ತರ', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದು',
    delete: 'ತೆಗೆದುಹಾಕಿ', complete: 'ಮುಗಿಸಿ', settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    language: 'ಭಾಷೆ', aiAssistant: 'AI ಕಲಿಕಾ ಸಹಾಯಕ',
    connectMicrosoft: 'Microsoft ನಿಂದ ಲಾಗಿನ್', syncNow: 'ಈಗ ಸಿಂಕ್',
    connected: 'ಸಂಪರ್ಕಿಸಲಾಗಿದೆ', disconnected: 'ಸಂಪರ್ಕಿಸಲಾಗಿಲ್ಲ',
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോര്‍ഡ്', tasks: 'ജോലികള്‍', weekly: 'ആഴ്ചതോരമായ', today: 'ഇന്ന്',
    emailSync: 'ഇമെയില്‍ സിങ്ക്', addTask: '+ ജോലി ചേര്‍ക്കുക', profile: 'പ്രൊഫൈല്‍',
    logout: 'ലോഗ്‌ഔട്ട്', changePassword: 'പാസ്‌വേര്‍ഡ് മാറ്റുക', welcome: 'സ്വാഗതം',
    yourTasks: 'നിങ്ങളുടെ ജോലികള്‍', noTasks: 'ഇതുവരെ ജോലികളില്ല', addNewTask: 'പുതിയ ജോലി ചേര്‍ക്കുക',
    editTask: 'ജോലി തിരുത്തുക', title: 'ശീര്‍ഷകം', description: 'വിവരണം',
    dueDate: 'അവസാന തിയതി', priority: 'മുന്‍ഗണന', course: 'കോഴ്സ്',
    low: 'കുറവ്', medium: 'ഇടത്തരം', high: 'ഉയര്‍ന്ന', save: 'സംരക്ഷിക്കുക', cancel: 'റദ്ദാക്കുക',
    delete: 'നീക്കം ചെയ്യുക', complete: 'പൂര്‍ത്തിയാക്കുക', settings: 'സെറ്റിംഗ്സ്',
    language: 'ഭാഷ', aiAssistant: 'AI പഠന സഹായി',
    connectMicrosoft: 'Microsoft വഴി ലോഗിന്‍', syncNow: 'ഇപ്പോള്‍ സിങ്ക് ചെയ്യുക',
    connected: 'ബന്ധിപ്പിച്ചിരിക്കുന്ന', disconnected: 'ബന്ധിപ്പിച്ചിട്ടില്ല',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ', tasks: 'ਕੰਮ', weekly: 'ਹਫ਼ਤਾਵਾਰੀ', today: 'ਅੱਜ',
    emailSync: 'ਈਮੇਲ ਸਿੰਕ', addTask: '+ ਕੰਮ ਜੋਡੋ', profile: 'ਪ੍ਰੋਫ਼ਾਈਲ',
    logout: 'ਲਾਗ ਆਊਟ', changePassword: 'ਪਾਸਵਰਡ ਬਦਲੋ', welcome: 'ਸਵਾਗਤ',
    yourTasks: 'ਤੁਹਾਡੇ ਕੰਮ', noTasks: 'ਹੋਰ ਕੋਈ ਕੰਮ ਨਹੀਂ', addNewTask: 'ਨਵਾਂ ਕੰਮ ਜੋਡੋ',
    editTask: 'ਕੰਮ ਸੰਪਾਦਿਤ ਕਰੋ', title: 'ਸਿਰਲੇਖ', description: 'ਵਰਣਨ',
    dueDate: 'ਅੰਤਿਮ ਤਾਰੀਖ', priority: 'ਤਰਜੀਹ', course: 'ਕੋਰਸ',
    low: 'ਘੱਟ', medium: 'ਵਿਚਕਾਰਲਾ', high: 'ਉੱਚਾ', save: 'ਸੇਵ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ',
    delete: 'ਹਟਾਓ', complete: 'ਪੂਰਾ ਕਰੋ', settings: 'ਸੈਟਿੰਗਸ',
    language: 'ਭਾਸ਼ਾ', aiAssistant: 'AI ਅਧਿਐਨ ਸਹਾਇਕ',
    connectMicrosoft: 'Microsoft ਨਾਲ ਲਾਗਿਨ', syncNow: 'ਹੁਣ ਸਿੰਕ ਕਰੋ',
    connected: 'ਕੁਨੈਕਟਿਡ', disconnected: 'ਡਿਸਕੁਨੈਕਟਿਡ',
  },
  or: {
    dashboard: 'ଡ୍ୟାଶବୋର୍ଡ', tasks: 'କାମ', weekly: 'ସାପ୍ତାହିକ', today: 'ଆଜ',
    emailSync: 'ଇମେଲ ସିଙ୍କ', addTask: '+ କାମ ଯୋଡ଼ିବେ', profile: 'ପ୍ରୋଫାଇଲ',
    logout: 'ଲଗଆଉଟ', changePassword: 'ପାସୱର୍ଡ ବଦଲାବେ', welcome: 'ସ୍ୱାଗତ',
    yourTasks: 'ତୁମର କାମ', noTasks: 'କୌଣସି କାମ ନାਹିଁ', addNewTask: 'ନୂତନ କାମ ଯୋଡ଼ିବେ',
    editTask: 'କାମ ସଂପାଦିତ କରୁଥିବେ', title: 'ଶୀର୍ଷକ', description: 'ବିବରଣୀ',
    dueDate: 'ଶେ਷ ତାਰੀਖ', priority: 'ପ୍ਰਾਥਮਿਕতਾ', course: 'କୋਰਸ',
    low: 'କମ', medium: 'ମଧ୍ਯਮ', high: 'ଉଚ୍ਚ', save: 'ସେਵ କਰੁ', cancel: 'ରଦ କਰୁ',
    delete: 'ହଟାବେ', complete: 'ସମ୍ਪੂਰ୍ਣ', settings: 'ସେਟਿੰਗਸ',
    language: 'ଭାଷਾ', aiAssistant: 'AI ଅଧ୍ਯୟਨ ସਹਾਇਕ',
    connectMicrosoft: 'Microsoft ସହ ଲଗଇਨ', syncNow: 'ଏବେ ସਿଙ୍କ କਰୁ',
    connected: 'ସଂਯੁਕਤ', disconnected: 'ଡਿਸਕੁਨੈਕਟਿਡ',
  },
  as: {
    dashboard: 'ডেশবোৰ্ড', tasks: 'কাম', weekly: 'সাপ্তাহিক', today: 'আজি',
    emailSync: 'ইমেইল চিঙ্ক', addTask: '+ কাম যোগ কৰক', profile: 'প্রফাইল',
    logout: 'লগ আউট', changePassword: 'পাছৱার্ড সলাও', welcome: 'স্বাগতম',
    yourTasks: 'আপোনাৰ কাম', noTasks: 'এতিয়াও কাম নাই', addNewTask: 'নতুন কাম যোগ কৰক',
    editTask: 'কাম সম্পাদনা কৰক', title: 'শীর্ষক', description: 'বিৱৰণ',
    dueDate: 'শেষ তাৰিখ', priority: 'প্রাধান্য', course: 'কোর্স',
    low: 'কম', medium: 'মধ্যম', high: 'উচ্চ', save: 'সংৰক্ষণ', cancel: 'বাতিল',
    delete: 'মচি দে', complete: 'সম্পূর্ণ', settings: 'ছেটিংছ',
    language: 'ভাষা', aiAssistant: 'AI অধ্যয়ন সহায়ক',
    connectMicrosoft: 'Microsoft ৰ মাধ্যমে লগ ইন', syncNow: 'এতিয়া চিঙ্ক কৰক',
    connected: 'সংযুক্ত', disconnected: 'বিচ্ছিন্ন',
  },
  ur: {
    dashboard: 'ڈیش بورڈ', tasks: 'کام', weekly: 'ہفتہ وار', today: 'آج',
    emailSync: 'ای میل سینک', addTask: '+ کام شامل کریں', profile: 'پروفائل',
    logout: 'لاگ آؤٹ', changePassword: 'پاسورڈ تبدیل کریں', welcome: 'خوش آمدید',
    yourTasks: 'آپ کے کام', noTasks: 'کوئی کام نہیں', addNewTask: 'نیا کام شامل کریں',
    editTask: 'کام ترمیم کریں', title: 'عنوان', description: 'تفصیل',
    dueDate: 'آخری تاریخ', priority: 'ترجیح', course: 'کورس',
    low: 'کم', medium: 'درمیانہ', high: 'اعلی', save: 'محفوظ کریں', cancel: 'منسوخ',
    delete: 'حذف کریں', complete: 'مکمل', settings: 'ترتیبات',
    language: 'زبان', aiAssistant: 'AI اسٹڈی اسسٹنٹ',
    connectMicrosoft: 'Microsoft سے لاگ ان کریں', syncNow: 'اب سینک کریں',
    connected: 'مقبول', disconnected: 'غیر متصل',
  },
  pt: {
    dashboard: 'Painel', tasks: 'Tarefas', weekly: 'Semanal', today: 'Hoje',
    emailSync: 'Sincronizar Email', addTask: '+ Adicionar Tarefa', profile: 'Perfil',
    logout: 'Sair', changePassword: 'Alterar Senha', welcome: 'Bem-vindo',
    yourTasks: 'Suas Tarefas', noTasks: 'Nenhuma tarefa ainda', addNewTask: 'Adicionar Nova Tarefa',
    editTask: 'Editar Tarefa', title: 'Título', description: 'Descrição',
    dueDate: 'Data de Vencimento', priority: 'Prioridade', course: 'Curso',
    low: 'Baixa', medium: 'Média', high: 'Alta', save: 'Salvar', cancel: 'Cancelar',
    delete: 'Excluir', complete: 'Concluir', settings: 'Configurações',
    language: 'Idioma', aiAssistant: 'Assistente de Estudo IA',
    connectMicrosoft: 'Entrar com Microsoft', syncNow: 'Sincronizar Agora',
    connected: 'Conectado', disconnected: 'Desconectado',
  },
  ja: {
    dashboard: 'ダッシュボード', tasks: 'タスク', weekly: '毎週', today: '今日',
    emailSync: 'メール同期', addTask: '+ タスクを追加', profile: 'プロフィール',
    logout: 'ログアウト', changePassword: 'パスワードを変更', welcome: 'ようこそ',
    yourTasks: 'あなたのタスク', noTasks: 'タスクはまだありません', addNewTask: '新しいタスクを追加',
    editTask: 'タスクを編集', title: 'タイトル', description: '説明',
    dueDate: '期限', priority: '優先度', course: 'コース',
    low: '低', medium: '中', high: '高', save: '保存', cancel: 'キャンセル',
    delete: '削除', complete: '完了', settings: '設定',
    language: '言語', aiAssistant: 'AI学習アシスタント',
    connectMicrosoft: 'Microsoftでサインイン', syncNow: '今すぐ同期',
    connected: '接続済み', disconnected: '未接続',
  },
  ko: {
    dashboard: '대시보드', tasks: '작업', weekly: '주간', today: '오늘',
    emailSync: '이메일 동기화', addTask: '+ 작업 추가', profile: '프로필',
    logout: '로그아웃', changePassword: '비밀번호 변경', welcome: '환영합니다',
    yourTasks: '내 작업', noTasks: '아직 작업이 없습니다', addNewTask: '새 작업 추가',
    editTask: '작업 편집', title: '제목', description: '설명',
    dueDate: '마감일', priority: '우선순위', course: '강좌',
    low: '낮음', medium: '중간', high: '높음', save: '저장', cancel: '취소',
    delete: '삭제', complete: '완료', settings: '설정',
    language: '언어', aiAssistant: 'AI 학습 도우미',
    connectMicrosoft: 'Microsoft로 로그인', syncNow: '지금 동기화',
    connected: '연결됨', disconnected: '연결 안됨',
  },
  ru: {
    dashboard: 'Панель', tasks: 'Задачи', weekly: 'Неделя', today: 'Сегодня',
    emailSync: 'Синхронизация почты', addTask: '+ Добавить задачу', profile: 'Профиль',
    logout: 'Выйти', changePassword: 'Изменить пароль', welcome: 'Добро пожаловать',
    yourTasks: 'Ваши задачи', noTasks: 'Пока нет задач', addNewTask: 'Добавить новую задачу',
    editTask: 'Редактировать задачу', title: 'Название', description: 'Описание',
    dueDate: 'Срок', priority: 'Приоритет', course: 'Курс',
    low: 'Низкий', medium: 'Средний', high: 'Высокий', save: 'Сохранить', cancel: 'Отмена',
    delete: 'Удалить', complete: 'Завершить', settings: 'Настройки',
    language: 'Язык', aiAssistant: 'AI Помощник по учебе',
    connectMicrosoft: 'Войти через Microsoft', syncNow: 'Синхронизировать',
    connected: 'Подключено', disconnected: 'Отключено',
  },
  it: {
    dashboard: 'Dashboard', tasks: 'Attività', weekly: 'Settimanale', today: 'Oggi',
    emailSync: 'Sincronizza Email', addTask: '+ Aggiungi Attività', profile: 'Profilo',
    logout: 'Esci', changePassword: 'Cambia Password', welcome: 'Benvenuto',
    yourTasks: 'Le tue attività', noTasks: 'Nessuna attività ancora', addNewTask: 'Aggiungi Nuova Attività',
    editTask: 'Modifica Attività', title: 'Titolo', description: 'Descrizione',
    dueDate: 'Data di scadenza', priority: 'Priorità', course: 'Corso',
    low: 'Bassa', medium: 'Media', high: 'Alta', save: 'Salva', cancel: 'Annulla',
    delete: 'Elimina', complete: 'Completa', settings: 'Impostazioni',
    language: 'Lingua', aiAssistant: 'Assistente Studio AI',
    connectMicrosoft: 'Accedi con Microsoft', syncNow: 'Sincronizza Ora',
    connected: 'Connesso', disconnected: 'Disconnesso',
  },
  tr: {
    dashboard: 'Panel', tasks: 'Görevler', weekly: 'Haftalık', today: 'Bugün',
    emailSync: 'E-posta Senkronizasyonu', addTask: '+ Görev Ekle', profile: 'Profil',
    logout: 'Çıkış Yap', changePassword: 'Parola Değiştir', welcome: 'Hoş geldiniz',
    yourTasks: 'Görevleriniz', noTasks: 'Henüz görev yok', addNewTask: 'Yeni Görev Ekle',
    editTask: 'Görevi Düzenle', title: 'Başlık', description: 'Açıklama',
    dueDate: 'Bitiş Tarihi', priority: 'Öncelik', course: 'Ders',
    low: 'Düşük', medium: 'Orta', high: 'Yüksek', save: 'Kaydet', cancel: 'İptal',
    delete: 'Sil', complete: 'Tamamla', settings: 'Ayarlar',
    language: 'Dil', aiAssistant: 'AI Çalışma Asistanı',
    connectMicrosoft: 'Microsoft ile giriş yap', syncNow: 'Şimdi Senkronize Et',
    connected: 'Bağlı', disconnected: 'Bağlı değil',
  },
  nl: {
    dashboard: 'Dashboard', tasks: 'Taken', weekly: 'Wekelijks', today: 'Vandaag',
    emailSync: 'E-mail synchronisatie', addTask: '+ Taak toevoegen', profile: 'Profiel',
    logout: 'Uitloggen', changePassword: 'Wachtwoord wijzigen', welcome: 'Welkom',
    yourTasks: 'Jouw taken', noTasks: 'Nog geen taken', addNewTask: 'Nieuwe taak toevoegen',
    editTask: 'Taak bewerken', title: 'Titel', description: 'Beschrijving',
    dueDate: 'Vervaldatum', priority: 'Prioriteit', course: 'Cursus',
    low: 'Laag', medium: 'Medium', high: 'Hoog', save: 'Opslaan', cancel: 'Annuleren',
    delete: 'Verwijderen', complete: 'Voltooien', settings: 'Instellingen',
    language: 'Taal', aiAssistant: 'AI Studie Assistent',
    connectMicrosoft: 'Aanmelden met Microsoft', syncNow: 'Nu synchroniseren',
    connected: 'Verbonden', disconnected: 'Niet verbonden',
  },
  pl: {
    dashboard: 'Pulpit', tasks: 'Zadania', weekly: 'Tygodniowy', today: 'Dzisiaj',
    emailSync: 'Synchronizacja e-mail', addTask: '+ Dodaj zadanie', profile: 'Profil',
    logout: 'Wyloguj', changePassword: 'Zmień hasło', welcome: 'Witaj',
    yourTasks: 'Twoje zadania', noTasks: 'Brak zadań', addNewTask: 'Dodaj nowe zadanie',
    editTask: 'Edytuj zadanie', title: 'Tytuł', description: 'Opis',
    dueDate: 'Termin', priority: 'Priorytet', course: 'Kurs',
    low: 'Niski', medium: 'Średni', high: 'Wysoki', save: 'Zapisz', cancel: 'Anuluj',
    delete: 'Usuń', complete: 'Zakończ', settings: 'Ustawienia',
    language: 'Język', aiAssistant: 'AI Asystent nauki',
    connectMicrosoft: 'Zaloguj się przez Microsoft', syncNow: 'Synchronizuj teraz',
    connected: 'Połączony', disconnected: 'Rozłączony',
  },
  sv: {
    dashboard: 'Instrumentpanel', tasks: 'Uppgifter', weekly: 'Veckovis', today: 'Idag',
    emailSync: 'E-postsynkronisering', addTask: '+ Lägg till uppgift', profile: 'Profil',
    logout: 'Logga ut', changePassword: 'Ändra lösenord', welcome: 'Välkommen',
    yourTasks: 'Dina uppgifter', noTasks: 'Inga uppgifter än', addNewTask: 'Lägg till ny uppgift',
    editTask: 'Redigera uppgift', title: 'Titel', description: 'Beskrivning',
    dueDate: 'Förfallodag', priority: 'Prioritet', course: 'Kurs',
    low: 'Låg', medium: 'Medel', high: 'Hög', save: 'Spara', cancel: 'Avbryt',
    delete: 'Ta bort', complete: 'Slutför', settings: 'Inställningar',
    language: 'Språk', aiAssistant: 'AI Studieassistent',
    connectMicrosoft: 'Logga in med Microsoft', syncNow: 'Synkronisera nu',
    connected: 'Ansluten', disconnected: 'Frånkopplad',
  },
  da: {
    dashboard: 'Dashboard', tasks: 'Opgaver', weekly: 'Ugentlig', today: 'I dag',
    emailSync: 'E-mail synkronisering', addTask: '+ Tilføj opgave', profile: 'Profil',
    logout: 'Log ud', changePassword: 'Skift adgangskode', welcome: 'Velkommen',
    yourTasks: 'Dine opgaver', noTasks: 'Ingen opgaver endnu', addNewTask: 'Tilføj ny opgave',
    editTask: 'Rediger opgave', title: 'Titel', description: 'Beskrivelse',
    dueDate: 'Forfaldsdag', priority: 'Prioritet', course: 'Kursus',
    low: 'Lav', medium: 'Medium', high: 'Høj', save: 'Gem', cancel: 'Annuller',
    delete: 'Slet', complete: 'Færdig', settings: 'Indstillinger',
    language: 'Sprog', aiAssistant: 'AI Studieassistent',
    connectMicrosoft: 'Log ind med Microsoft', syncNow: 'Synkroniser nu',
    connected: 'Tilsluttet', disconnected: 'Frakoblet',
  },
  no: {
    dashboard: 'Dashbord', tasks: 'Oppgaver', weekly: 'Ukentlig', today: 'I dag',
    emailSync: 'E-post synkronisering', addTask: '+ Legg til oppgave', profile: 'Profil',
    logout: 'Logg ut', changePassword: 'Endre passord', welcome: 'Velkommen',
    yourTasks: 'Dine oppgaver', noTasks: 'Ingen oppgaver ennå', addNewTask: 'Legg til ny oppgave',
    editTask: 'Rediger oppgave', title: 'Tittel', description: 'Beskrivelse',
    dueDate: 'Forfallsdato', priority: 'Prioritet', course: 'Kurs',
    low: 'Lav', medium: 'Medium', high: 'Høy', save: 'Lagre', cancel: 'Avbryt',
    delete: 'Slett', complete: 'Fullfør', settings: 'Innstillinger',
    language: 'Språk', aiAssistant: 'AI Studieassistent',
    connectMicrosoft: 'Logg inn med Microsoft', syncNow: 'Synkroniser nå',
    connected: 'Tilkoblet', disconnected: 'Frakoblet',
  },
  fi: {
    dashboard: 'Kojelauta', tasks: 'Tehtävät', weekly: 'Viikottain', today: 'Tänään',
    emailSync: 'Sähköpostin synkronointi', addTask: '+ Lisää tehtävä', profile: 'Profiili',
    logout: 'Kirjaudu ulos', changePassword: 'Vaihda salasana', welcome: 'Tervetuloa',
    yourTasks: 'Tehtäväsi', noTasks: 'Ei vielä tehtäviä', addNewTask: 'Lisää uusi tehtävä',
    editTask: 'Muokkaa tehtävää', title: 'Otsikko', description: 'Kuvaus',
    dueDate: 'Eräpäivä', priority: 'Prioriteetti', course: 'Kurssi',
    low: 'Matala', medium: 'Keskitaso', high: 'Korkea', save: 'Tallenna', cancel: 'Peruuta',
    delete: 'Poista', complete: 'Valmis', settings: 'Asetukset',
    language: 'Kieli', aiAssistant: 'AI Opiskeluavustaja',
    connectMicrosoft: 'Kirjaudu Microsoftilla', syncNow: 'Synkronoi nyt',
    connected: 'Yhdistetty', disconnected: 'Ei yhdistetty',
  },
  th: {
    dashboard: 'แดชบอร์ด', tasks: 'งาน', weekly: 'รายสัปดาห์', today: 'วันนี้',
    emailSync: 'ซิงโครไนซ์อีเมล', addTask: '+ เพิ่มงาน', profile: 'โปรไฟล์',
    logout: 'ออกจากระบบ', changePassword: 'เปลี่ยนรหัสผ่าน', welcome: 'ยินดีต้อนรับ',
    yourTasks: 'งานของคุณ', noTasks: 'ยังไม่มีงาน', addNewTask: 'เพิ่มงานใหม่',
    editTask: 'แก้ไขงาน', title: 'หัวข้อ', description: 'รายละเอียด',
    dueDate: 'กำหนดส่ง', priority: 'ลำดับความสำคัญ', course: 'วิชา',
    low: 'ต่ำ', medium: 'ปานกลาง', high: 'สูง', save: 'บันทึก', cancel: 'ยกเลิก',
    delete: 'ลบ', complete: 'เสร็จสิ้น', settings: 'การตั้งค่า',
    language: 'ภาษา', aiAssistant: 'ผู้ช่วย AI การเรียน',
    connectMicrosoft: 'เข้าสู่ระบบด้วย Microsoft', syncNow: 'ซิงโครไนซ์ตอนนี้',
    connected: 'เชื่อมต่อแล้ว', disconnected: 'ไม่ได้เชื่อมต่อ',
  },
  vi: {
    dashboard: 'Bảng điều khiển', tasks: 'Công việc', weekly: 'Hàng tuần', today: 'Hôm nay',
    emailSync: 'Đồng bộ email', addTask: '+ Thêm công việc', profile: 'Hồ sơ',
    logout: 'Đăng xuất', changePassword: 'Đổi mật khẩu', welcome: 'Chào mừng',
    yourTasks: 'Công việc của bạn', noTasks: 'Chưa có công việc', addNewTask: 'Thêm công việc mới',
    editTask: 'Sửa công việc', title: 'Tiêu đề', description: 'Mô tả',
    dueDate: 'Ngày đến hạn', priority: 'Ưu tiên', course: 'Khóa học',
    low: 'Thấp', medium: 'Trung bình', high: 'Cao', save: 'Lưu', cancel: 'Hủy',
    delete: 'Xóa', complete: 'Hoàn thành', settings: 'Cài đặt',
    language: 'Ngôn ngữ', aiAssistant: 'Trợ lý AI học tập',
    connectMicrosoft: 'Đăng nhập bằng Microsoft', syncNow: 'Đồng bộ ngay',
    connected: 'Đã kết nối', disconnected: 'Chưa kết nối',
  },
  id: {
    dashboard: 'Dasbor', tasks: 'Tugas', weekly: 'Mingguan', today: 'Hari ini',
    emailSync: 'Sinkronisasi email', addTask: '+ Tambah tugas', profile: 'Profil',
    logout: 'Keluar', changePassword: 'Ubah kata sandi', welcome: 'Selamat datang',
    yourTasks: 'Tugas Anda', noTasks: 'Belum ada tugas', addNewTask: 'Tambah tugas baru',
    editTask: 'Edit tugas', title: 'Judul', description: 'Deskripsi',
    dueDate: 'Tanggal jatuh tempo', priority: 'Prioritas', course: 'Kursus',
    low: 'Rendah', medium: 'Sedang', high: 'Tinggi', save: 'Simpan', cancel: 'Batal',
    delete: 'Hapus', complete: 'Selesai', settings: 'Pengaturan',
    language: 'Bahasa', aiAssistant: 'Asisten belajar AI',
    connectMicrosoft: 'Masuk dengan Microsoft', syncNow: 'Sinkronkan sekarang',
    connected: 'Terhubung', disconnected: 'Tidak terhubung',
  },
  ms: {
    dashboard: 'Papan pemuka', tasks: 'Tugas', weekly: 'Mingguan', today: 'Hari ini',
    emailSync: 'Selaras e-mel', addTask: '+ Tambah tugas', profile: 'Profil',
    logout: 'Log keluar', changePassword: 'Tukar kata laluan', welcome: 'Selamat datang',
    yourTasks: 'Tugas anda', noTasks: 'Belum ada tugas', addNewTask: 'Tambah tugas baharu',
    editTask: 'Edit tugas', title: 'Tajuk', description: 'Perihal',
    dueDate: 'Tarikh akhir', priority: 'Keutamaan', course: 'Kursus',
    low: 'Rendah', medium: 'Sederhana', high: 'Tinggi', save: 'Simpan', cancel: 'Batal',
    delete: 'Padam', complete: 'Selesai', settings: 'Tetapan',
    language: 'Bahasa', aiAssistant: 'Pembantu AI Pembelajaran',
    connectMicrosoft: 'Log masuk dengan Microsoft', syncNow: 'Selaras sekarang',
    connected: 'Disambung', disconnected: 'Tidak disambung',
  },
  uk: {
    dashboard: 'Панель', tasks: 'Завдання', weekly: 'Тижневий', today: 'Сьогодні',
    emailSync: 'Синхронізація пошти', addTask: '+ Додати завдання', profile: 'Профіль',
    logout: 'Вийти', changePassword: 'Змінити пароль', welcome: 'Ласкаво просимо',
    yourTasks: 'Ваші завдання', noTasks: 'Завдань ще немає', addNewTask: 'Додати нове завдання',
    editTask: 'Редагувати завдання', title: 'Назва', description: 'Опис',
    dueDate: 'Термін', priority: 'Пріоритет', course: 'Курс',
    low: 'Низький', medium: 'Середній', high: 'Високий', save: 'Зберегти', cancel: 'Скасувати',
    delete: 'Видалити', complete: 'Завершити', settings: 'Налаштування',
    language: 'Мова', aiAssistant: 'AI Помічник навчання',
    connectMicrosoft: 'Увійти через Microsoft', syncNow: 'Синхронізувати',
    connected: 'Підключено', disconnected: 'Відключено',
  },
  cs: {
    dashboard: 'Nástěnka', tasks: 'Úkoly', weekly: 'Týdenní', today: 'Dnes',
    emailSync: 'Synchronizace e-mailu', addTask: '+ Přidat úkol', profile: 'Profil',
    logout: 'Odhlásit se', changePassword: 'Změnit heslo', welcome: 'Vítejte',
    yourTasks: 'Vaše úkoly', noTasks: 'Zatím žádné úkoly', addNewTask: 'Přidat nový úkol',
    editTask: 'Upravit úkol', title: 'Název', description: 'Popis',
    dueDate: 'Termín', priority: 'Priorita', course: 'Kurz',
    low: 'Nízká', medium: 'Střední', high: 'Vysoká', save: 'Uložit', cancel: 'Zrušit',
    delete: 'Smazat', complete: 'Dokončit', settings: 'Nastavení',
    language: 'Jazyk', aiAssistant: 'AI Studijní asistent',
    connectMicrosoft: 'Přihlásit přes Microsoft', syncNow: 'Synchronizovat',
    connected: 'Připojeno', disconnected: 'Odpojeno',
  },
  el: {
    dashboard: 'Πίνακας ελέγχου', tasks: 'Εργασίες', weekly: 'Εβδομαδιαίο', today: 'Σήμερα',
    emailSync: 'Συγχρονισμός email', addTask: '+ Προσθήκη εργασίας', profile: 'Προφίλ',
    logout: 'Αποσύνδεση', changePassword: 'Αλλαγή κωδικού', welcome: 'Καλώς ήρθες',
    yourTasks: 'Οι εργασίες σου', noTasks: 'Δεν υπάρχουν εργασίες', addNewTask: 'Προσθήκη νέας εργασίας',
    editTask: 'Επεξεργασία εργασίας', title: 'Τίτλος', description: 'Περιγραφή',
    dueDate: 'Ημερομηνία λήξης', priority: 'Προτεραιότητα', course: 'Μάθημα',
    low: 'Χαμηλή', medium: 'Μέτρια', high: 'Υψηλή', save: 'Αποθήκευση', cancel: 'Ακύρωση',
    delete: 'Διαγραφή', complete: 'Ολοκλήρωση', settings: 'Ρυθμίσεις',
    language: 'Γλώσσα', aiAssistant: 'Βοηθός AI μάθησης',
    connectMicrosoft: 'Σύνδεση με Microsoft', syncNow: 'Συγχρονισμός τώρα',
    connected: 'Συνδεδεμένο', disconnected: 'Αποσυνδεδεμένο',
  },
  he: {
    dashboard: 'לוח בקרה', tasks: 'משימות', weekly: 'שבועי', today: 'היום',
    emailSync: 'סנכרון דואר', addTask: '+ הוסף משימה', profile: 'פרופיל',
    logout: 'התנתק', changePassword: 'שנה סיסמה', welcome: 'ברוך הבא',
    yourTasks: 'המשימות שלך', noTasks: 'אין משימות עדיין', addNewTask: 'הוסף משימה חדשה',
    editTask: 'ערוך משימה', title: 'כותרת', description: 'תיאור',
    dueDate: 'תאריך יעד', priority: 'עדיפות', course: 'קורס',
    low: 'נמוכה', medium: 'בינונית', high: 'גבוהה', save: 'שמור', cancel: 'בטל',
    delete: 'מחק', complete: 'השלם', settings: 'הגדרות',
    language: 'שפה', aiAssistant: 'עוזר AI ללימודים',
    connectMicrosoft: 'התחבר עם Microsoft', syncNow: 'סנכרן עכשיו',
    connected: 'מחובר', disconnected: 'מנותק',
  },
  hu: {
    dashboard: 'Irányítópult', tasks: 'Feladatok', weekly: 'Heti', today: 'Ma',
    emailSync: 'E-mail szinkronizálás', addTask: '+ Feladat hozzáadása', profile: 'Profil',
    logout: 'Kijelentkezés', changePassword: 'Jelszó módosítása', welcome: 'Üdvözöljük',
    yourTasks: 'A feladataid', noTasks: 'Még nincs feladat', addNewTask: 'Új feladat hozzáadása',
    editTask: 'Feladat szerkesztése', title: 'Cím', description: 'Leírás',
    dueDate: 'Határidő', priority: 'Prioritás', course: 'Kurzus',
    low: 'Alacsony', medium: 'Közepes', high: 'Magas', save: 'Mentés', cancel: 'Mégse',
    delete: 'Törlés', complete: 'Befejezés', settings: 'Beállítások',
    language: 'Nyelv', aiAssistant: 'AI Tanulási Asszisztens',
    connectMicrosoft: 'Bejelentkezés Microsoft-fiókkal', syncNow: 'Szinkronizálás most',
    connected: 'Csatlakoztatva', disconnected: 'Leválasztva',
  },
  ro: {
    dashboard: 'Panou', tasks: 'Activități', weekly: 'Săptămânal', today: 'Astăzi',
    emailSync: 'Sincronizare e-mail', addTask: '+ Adaugă activitate', profile: 'Profil',
    logout: 'Deconectare', changePassword: 'Schimbă parola', welcome: 'Bine ai venit',
    yourTasks: 'Activitățile tale', noTasks: 'Încă nu există activități', addNewTask: 'Adaugă activitate nouă',
    editTask: 'Editează activitatea', title: 'Titlu', description: 'Descriere',
    dueDate: 'Termen limită', priority: 'Prioritate', course: 'Curs',
    low: 'Scăzută', medium: 'Medie', high: 'Ridicată', save: 'Salvează', cancel: 'Anulează',
    delete: 'Șterge', complete: 'Finalizează', settings: 'Setări',
    language: 'Limbă', aiAssistant: 'Asistent AI de studiu',
    connectMicrosoft: 'Conectează-te cu Microsoft', syncNow: 'Sincronizează acum',
    connected: 'Conectat', disconnected: 'Deconectat',
  },
  sk: {
    dashboard: 'Nástenka', tasks: 'Úlohy', weekly: 'Týždenný', today: 'Dnes',
    emailSync: 'Synchronizácia e-mailu', addTask: '+ Pridať úlohu', profile: 'Profil',
    logout: 'Odhlásiť sa', changePassword: 'Zmeniť heslo', welcome: 'Vitajte',
    yourTasks: 'Vaše úlohy', noTasks: 'Zatiaľ žiadne úlohy', addNewTask: 'Pridať novú úlohu',
    editTask: 'Upraviť úlohu', title: 'Názov', description: 'Popis',
    dueDate: 'Termín', priority: 'Priorita', course: 'Kurz',
    low: 'Nízka', medium: 'Stredná', high: 'Vysoká', save: 'Uložiť', cancel: 'Zrušiť',
    delete: 'Vymazať', complete: 'Dokončiť', settings: 'Nastavenia',
    language: 'Jazyk', aiAssistant: 'AI Študijný asistent',
    connectMicrosoft: 'Prihlásiť sa cez Microsoft', syncNow: 'Synchronizovať',
    connected: 'Pripojené', disconnected: 'Odpojené',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড', tasks: 'কাজ', weekly: 'সাপ্তাহিক', today: 'আজ',
    emailSync: 'ইমেইল সিঙ্ক', addTask: '+ কাজ যোগ করুন', profile: 'প্রোফাইল',
    logout: 'লগ আউট', changePassword: 'পাসওয়ার্ড পরিবর্তন', welcome: 'স্বাগতম',
    yourTasks: 'আপনার কাজ', noTasks: 'এখনও কোন কাজ নেই', addNewTask: 'নতুন কাজ যোগ করুন',
    editTask: 'কাজ সম্পাদনা', title: 'শিরোনাম', description: 'বিবরণ',
    dueDate: 'নির্ধারিত তারিখ', priority: 'অগ্রাধিকার', course: 'কোর্স',
    low: 'কম', medium: 'মাঝারি', high: 'উচ্চ', save: 'সংরক্ষণ', cancel: 'বাতিল',
    delete: 'মুছুন', complete: 'সম্পন্ন', settings: 'সেটিংস',
    language: 'ভাষা', aiAssistant: 'AI অধ্যয়ন সহায়ক',
    connectMicrosoft: 'Microsoft দিয়ে লগ ইন', syncNow: 'এখন সিঙ্ক করুন',
    connected: 'সংযুক্ত', disconnected: 'সংযুক্ত নেই',
  },
  'zh-TW': {
    dashboard: '儀表板', tasks: '任務', weekly: '每週', today: '今天',
    emailSync: '郵件同步', addTask: '+ 添加任務', profile: '個人資料',
    logout: '登出', changePassword: '更改密碼', welcome: '歡迎',
    yourTasks: '您的任務', noTasks: '暫無任務', addNewTask: '添加新任務',
    editTask: '編輯任務', title: '標題', description: '描述',
    dueDate: '截止日期', priority: '優先級', course: '課程',
    low: '低', medium: '中', high: '高', save: '儲存', cancel: '取消',
    delete: '刪除', complete: '完成', settings: '設定',
    language: '語言', aiAssistant: 'AI學習助手',
    connectMicrosoft: '使用Microsoft登入', syncNow: '立即同步',
    connected: '已連接', disconnected: '未連接',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
    const rtlLanguages = ['ar', 'he', 'fa', 'ur'];
    document.documentElement.dir = rtlLanguages.includes(language) ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}

export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'he', name: 'עברית', flag: '🇮🇱' },
  { code: 'hi', name: 'हिन्दी (Hindi)', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ் (Tamil)', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు (Telugu)', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी (Marathi)', flag: '🇮🇳' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)', flag: '🇮🇳' },
  { code: 'kn', name: 'ಕನ್ನಡ (Kannada)', flag: '🇮🇳' },
  { code: 'ml', name: 'മലയാളം (Malayalam)', flag: '🇮🇳' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)', flag: '🇮🇳' },
  { code: 'or', name: 'ଓଡ଼ିଆ (Odia)', flag: '🇮🇳' },
  { code: 'as', name: 'অসমীয়া (Assamese)', flag: '🇮🇳' },
  { code: 'ur', name: 'اردو (Urdu)', flag: '🇮🇳' },
  { code: 'bn', name: 'বাংলা (Bengali)', flag: '🇧🇩' },
  { code: 'zh', name: '简体中文', flag: '🇨🇳' },
  { code: 'zh-TW', name: '繁體中文', flag: '🇹🇼' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
  { code: 'da', name: 'Dansk', flag: '🇩🇰' },
  { code: 'no', name: 'Norsk', flag: '🇳🇴' },
  { code: 'fi', name: 'Suomi', flag: '🇫🇮' },
  { code: 'th', name: 'ไทย', flag: '🇹🇭' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ms', name: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'uk', name: 'Українська', flag: '🇺🇦' },
  { code: 'cs', name: 'Čeština', flag: '🇨🇿' },
  { code: 'el', name: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'hu', name: 'Magyar', flag: '🇭🇺' },
  { code: 'ro', name: 'Română', flag: '🇷🇴' },
  { code: 'sk', name: 'Slovenčina', flag: '🇸🇰' },
];
