import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard', tasks: 'Tasks', weekly: 'Weekly', monthly: 'Monthly', today: 'Today',
    emailSync: 'Email Sync', addTask: '+ Add Task', profile: 'Profile', logout: 'Logout',
    changePassword: 'Change Password', welcome: 'Welcome', yourTasks: 'Your Tasks',
    noTasks: 'No tasks yet', addNewTask: 'Add New Task', editTask: 'Edit Task',
    title: 'Title', description: 'Description', dueDate: 'Due Date', priority: 'Priority',
    course: 'Course', low: 'Low', medium: 'Medium', high: 'High',
    save: 'Save', cancel: 'Cancel', delete: 'Delete', complete: 'Complete',
    settings: 'Settings', language: 'Language', aiAssistant: 'AI Study Assistant',
    connectMicrosoft: 'Sign in with Microsoft', syncNow: 'Sync Now',
    connected: 'Connected', disconnected: 'Disconnected',
    taskAdded: 'Task added successfully!', failedToAdd: 'Failed to add task: ',
    taskUpdated: 'Task updated successfully!', failedToUpdate: 'Failed to update task: ',
    taskDeleted: 'Task deleted successfully!', failedToDelete: 'Failed to delete task: ',
    failedToUpdateTask: 'Failed to update task: ',
    deleteConfirm: 'Are you sure you want to delete this task?',
    loadingTasks: 'Loading tasks...',
    email: 'Email', password: 'Password', name: 'Name',
    login: 'Login', register: 'Register', dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?', signUp: 'Sign Up', signIn: 'Sign In',
    welcomeBack: 'Welcome Back', createAccount: 'Create Account',
    manageTasks: 'Manage your tasks and stay organized',
    notifications: 'Notifications', noNotifications: 'No notifications',
    markAllRead: 'Mark all as read', noDueDate: 'No due date',
    overdue: 'Overdue', dueToday: 'Due Today', dueTomorrow: 'Due Tomorrow',
    upcoming: 'Upcoming', completed: 'Completed', pending: 'Pending',
    all: 'All', filterBy: 'Filter by', sortBy: 'Sort by', search: 'Search',
    duration: 'Duration', minutes: 'minutes', hours: 'hours',
    taskDetails: 'Task Details', noDescription: 'No description',
    edit: 'Edit', close: 'Close', select: 'Select', update: 'Update', 
    smartEmailSync: 'Smart Email Sync', importAssignments: 'Automatically import assignments from your university email',
    howItWorks: 'How It Works', signInMicrosoft: 'Click "Sign in with Microsoft" to connect your university account',
    grantPermission: 'Grant permission to read your emails (Planora only reads subjects)',
    clickSync: 'Click "Sync Now" to import your recent assignments',
    automaticSync: 'Automatic sync runs every 15 minutes',
    taggedAs: 'Tasks are tagged as "Assignment" or "Announcement"',
    accountConnected: 'Account connected successfully!', disconnect: 'Disconnect',
    tokenActive: 'Active', tokenNeedsRefresh: 'Needs refresh',
    syncing: 'Syncing...', syncComplete: 'Sync completed! New tasks added to dashboard.',
    syncError: 'Sync error: ',
    errorConnecting: 'Error connecting: ', token: 'Token',
    todaysPlan: "Today's Plan", recommendedForYou: 'Recommended for you',
    basedOnPriority: 'Based on your task priorities and deadlines',
    noTasksToday: 'No tasks due today. Enjoy your free time!',
    noTasksMatch: 'No tasks match your search',
    weeklyOverview: 'Weekly Overview', workloadDistribution: 'Workload Distribution',
    noTasksThisWeek: 'No tasks scheduled for this week',
    previousWeek: 'Previous Week', nextWeek: 'Next Week', thisWeek: 'This Week',
    monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday',
    friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
    loading: 'Loading...', unknown: 'Unknown', loadingAccount: 'Loading...',
    accountInfo: 'Account Information', emailAddress: 'Email Address',
    newPassword: 'New Password', enterNewPassword: 'Enter new password',
    error: 'Error', success: 'Success', pleaseWait: 'Please wait...',
    addFirstTask: 'Add your first task!', noTasksYet: 'No tasks yet. Add your first task!',
    viewAll: 'View All', markComplete: 'Mark Complete', markIncomplete: 'Mark Incomplete',
    todayAt: 'Today at', tomorrowAt: 'Tomorrow at',
    focusMode: 'Focus Mode', selectDuration: 'Select Duration', min: 'min',
    startFocus: 'Start Focus', pause: 'Pause', resume: 'Resume', reset: 'Reset',
    ready: 'Ready', focusing: 'Focusing', paused: 'Paused',
    sessionsToday: 'Sessions Today', enableNotifications: 'Enable notifications for reminders',
    enable: 'Enable', set: 'Set',     focusComplete: 'Great job! Take a short break.',
    backToWork: "Welcome back! Let's get back to focused work.",
    aiAccounts: 'AI Accounts', aiSettingsDesc: 'Connect your AI provider accounts to use different AI models in the chatbot.',
    aiPrivacyNote: 'Planora does not store your credentials. Authentication is handled securely by the providers.',
    enterApiKey: 'Enter API Key',
    generatingPlan: 'Generating your plan...',
    noPendingTasks: "No pending tasks! You're all caught up.",
    addTasksFromDashboard: 'Add tasks from the Dashboard to get personalized recommendations.',
    loadingCalendar: 'Loading calendar...',
    tasksManagement: 'Tasks management page placeholder',
    enterYourEmail: 'Enter your email',
    enterPassword: 'Enter password',
    defaultDuration: '60',
    refresh: 'Refresh',
    tasksPending: 'Tasks Pending',
    completedToday: 'Completed Today',
    tasksRanked: "Tasks are ranked by priority, urgency, and duration to help you focus on what matters most.",
    recommendedTaskOrder: 'Recommended Task Order',
    hours: 'h workload',
    askMeAnything: 'Ask me anything...',
    send: 'Send',
    noLanguagesFound: 'No languages found',
    monthlyOverview: 'Monthly Overview',
    dashboardHomeSubtitle: 'Your command center—see what matters today and jump into planning.',
    statOverdue: 'Overdue (open)',
    statDueToday: 'Due today',
    statHighPriority: 'High priority (open)',
    statCompletedWeek: 'Completed this week',
    dashboardStatsAria: 'Task summary statistics',
    focusNextTasks: 'Focus next',
    focusNextTasksHint: 'Top open tasks by urgency—check these first.',
    focusEmpty: 'Nothing urgent right now. Add a task or enjoy the calm.',
    thisWeekWorkload: 'This week (scheduled)',
    workloadDaysWithTasks: 'Days with tasks',
    workloadOpenTasks: 'Open tasks due',
    workloadEstTime: 'Est. time (open)',
    hoursShort: 'h',
    minutesShort: 'm',
    filterActive: 'Active',
    priorityAll: 'All priorities',
    allCourses: 'All courses',
    displayDensity: 'List density',
    densityComfortable: 'Comfortable',
    densityCompact: 'Compact',
    tasksPageSubtitle: 'Search, filter, and manage your full task library.',
    taskLibrary: 'Task library',
  },
  es: {
    dashboard: 'Panel', tasks: 'Tareas', weekly: 'Semanal', monthly: 'Mensual', today: 'Hoy',
    emailSync: 'Sincronizar Email', addTask: '+ Agregar Tarea', profile: 'Perfil',
    logout: 'Cerrar Sesión', changePassword: 'Cambiar Contraseña', welcome: 'Bienvenido',
    yourTasks: 'Tus Tareas', noTasks: 'Sin tareas aún', addNewTask: 'Agregar Nueva Tarea',
    editTask: 'Editar Tarea', title: 'Título', description: 'Descripción',
    dueDate: 'Fecha de Vencimiento', priority: 'Prioridad', course: 'Curso',
    low: 'Baja', medium: 'Media', high: 'Alta', save: 'Guardar', cancel: 'Cancelar',
    delete: 'Eliminar', complete: 'Completar', settings: 'Configuración',
    language: 'Idioma', aiAssistant: 'Asistente de Estudio IA',
    connectMicrosoft: 'Iniciar sesión con Microsoft', syncNow: 'Sincronizar Ahora',
    connected: 'Conectado', disconnected: 'Desconectado',
    taskAdded: '¡Tarea agregada!', failedToAdd: 'Error al agregar tarea: ',
    taskUpdated: '¡Tarea actualizada!', failedToUpdate: 'Error al actualizar tarea: ',
    taskDeleted: '¡Tarea eliminada!', failedToDelete: 'Error al eliminar tarea: ',
    failedToUpdateTask: 'Error al actualizar tarea: ',
    deleteConfirm: '¿Estás seguro de eliminar esta tarea?',
    loadingTasks: 'Cargando tareas...',
    email: 'Correo electrónico', password: 'Contraseña', name: 'Nombre',
    login: 'Iniciar sesión', register: 'Registrarse', dontHaveAccount: '¿No tienes una cuenta?',
    alreadyHaveAccount: '¿Ya tienes una cuenta?', signUp: 'Registrarse', signIn: 'Iniciar sesión',
    welcomeBack: 'Bienvenido de nuevo', createAccount: 'Crear cuenta',
    manageTasks: 'Gestiona tus tareas y mantente organizado',
    notifications: 'Notificaciones', noNotifications: 'Sin notificaciones',
    markAllRead: 'Marcar todo como leído', noDueDate: 'Sin fecha de vencimiento',
    overdue: 'Atrasado', dueToday: 'Hoy', dueTomorrow: 'Mañana',
    upcoming: 'Próximo', completed: 'Completado', pending: 'Pendiente',
    all: 'Todos', filterBy: 'Filtrar por', sortBy: 'Ordenar por', search: 'Buscar',
    duration: 'Duración', minutes: 'minutos', hours: 'h de trabajo',
    taskDetails: 'Detalles de la tarea', noDescription: 'Sin descripción',
    edit: 'Editar', close: 'Cerrar', select: 'Seleccionar', update: 'Actualizar',
    smartEmailSync: 'Sincronización inteligente de correo',
    importAssignments: 'Importar tareas automáticamente desde tu correo universitario',
    howItWorks: 'Cómo funciona',
    signInMicrosoft: 'Haz clic en "Iniciar sesión con Microsoft" para conectar tu cuenta universitaria',
    grantPermission: 'Otorga permiso para leer tus correos (Planora solo lee los asuntos)',
    clickSync: 'Haz clic en "Sincronizar Ahora" para importar tus tareas recientes',
    automaticSync: 'La sincronización automática se ejecuta cada 15 minutos',
    taggedAs: 'Las tareas se etiquetan como "Tarea" o "Anuncio"',
    accountConnected: '¡Cuenta conectada exitosamente!', disconnect: 'Desconectar',
    tokenActive: 'Activo', tokenNeedsRefresh: 'Necesita actualización',
    syncing: 'Sincronizando...', syncComplete: '¡Sincronización completada! Nuevas tareas agregadas al panel.',
    syncError: 'Error de sincronización: ',
    errorConnecting: 'Error al conectar: ', token: 'Token',
    todaysPlan: 'Plan de hoy', recommendedForYou: 'Recomendado para ti',
    basedOnPriority: 'Basado en tus prioridades de tareas y fechas límite',
    noTasksToday: 'No hay tareas para hoy. ¡Disfruta tu tiempo libre!',
    noTasksMatch: 'Ninguna tarea coincide con tu búsqueda',
    weeklyOverview: 'Vista Semanal', workloadDistribution: 'Distribución de carga de trabajo',
    noTasksThisWeek: 'No hay tareas programadas para esta semana',
    previousWeek: 'Semana anterior', nextWeek: 'Semana siguiente', thisWeek: 'Esta semana',
    monday: 'Lunes', tuesday: 'Martes', wednesday: 'Miércoles', thursday: 'Jueves',
    friday: 'Viernes', saturday: 'Sábado', sunday: 'Domingo',
    mon: 'Lun', tue: 'Mar', wed: 'Mié', thu: 'Jue', fri: 'Vie', sat: 'Sáb', sun: 'Dom',
    loading: 'Cargando...', unknown: 'Desconocido', loadingAccount: 'Cargando...',
    accountInfo: 'Información de la cuenta', emailAddress: 'Dirección de correo',
    newPassword: 'Nueva contraseña', enterNewPassword: 'Ingresa nueva contraseña',
    error: 'Error', success: 'Éxito', pleaseWait: 'Por favor espera...',
    addFirstTask: '¡Agrega tu primera tarea!', noTasksYet: 'Sin tareas aún. ¡Agrega tu primera tarea!',
    viewAll: 'Ver todo', markComplete: 'Marcar como completado', markIncomplete: 'Marcar como incompleto',
    todayAt: 'Hoy a las', tomorrowAt: 'Mañana a las',
    focusMode: 'Modo Enfoque', selectDuration: 'Seleccionar duración', min: 'min',
    startFocus: 'Iniciar Enfoque', pause: 'Pausar', resume: 'Continuar', reset: 'Reiniciar',
    ready: 'Listo', focusing: 'Enfocado', paused: 'Pausado',
    sessionsToday: 'Sesiones hoy', enableNotifications: 'Habilitar notificaciones para recordatorios',
    enable: 'Habilitar', set: 'Establecer', focusComplete: '¡Buen trabajo! Toma un descanso corto.',
    backToWork: '¡Bienvenido de nuevo! Volvamos al trabajo enfocado.',
    aiAccounts: 'Cuentas de IA', aiSettingsDesc: 'Conecta tus cuentas de proveedores de IA para usar diferentes modelos en el chatbot.',
    aiPrivacyNote: 'Planora no almacena tus credenciales. La autenticación es gestionada de forma segura por los proveedores.',
    enterApiKey: 'Ingresar clave API',
    generatingPlan: 'Generando tu plan...',
    noPendingTasks: '¡Sin tareas pendientes! Estás al día.',
    addTasksFromDashboard: 'Agrega tareas desde el Panel para obtener recomendaciones personalizadas.',
    loadingCalendar: 'Cargando calendario...',
    tasksManagement: 'Página de gestión de tareas',
    enterYourEmail: 'Tu correo electrónico',
    enterPassword: 'Contraseña',
    defaultDuration: '60',
    refresh: 'Actualizar',
    tasksPending: 'Tareas Pendientes',
    completedToday: 'Completadas Hoy',
    tasksRanked: 'Las tareas se ordenan por prioridad, urgencia y duración para ayudarte a enfocarte en lo más importante.',
    recommendedTaskOrder: 'Orden Recomendado',
    askMeAnything: 'Pregúntame...',
    send: 'Enviar',
    noLanguagesFound: 'No se encontraron idiomas',
    monthlyOverview: 'Vista Mensual',
    dashboardHomeSubtitle: 'Tu centro de mando: lo importante hoy y accesos rápidos.',
    statOverdue: 'Atrasadas (abiertas)',
    statDueToday: 'Para hoy',
    statHighPriority: 'Alta prioridad (abiertas)',
    statCompletedWeek: 'Completadas esta semana',
    dashboardStatsAria: 'Resumen de tareas',
    focusNextTasks: 'Enfócate en',
    focusNextTasksHint: 'Tareas abiertas más urgentes.',
    focusEmpty: 'Nada urgente ahora. Añade una tarea o disfruta el momento.',
    thisWeekWorkload: 'Esta semana (programadas)',
    workloadDaysWithTasks: 'Días con tareas',
    workloadOpenTasks: 'Tareas abiertas',
    workloadEstTime: 'Tiempo est. (abiertas)',
    hoursShort: 'h',
    minutesShort: 'm',
    filterActive: 'Activas',
    priorityAll: 'Todas las prioridades',
    allCourses: 'Todos los cursos',
    displayDensity: 'Densidad de lista',
    densityComfortable: 'Cómoda',
    densityCompact: 'Compacta',
    tasksPageSubtitle: 'Busca, filtra y gestiona todas tus tareas.',
    taskLibrary: 'Biblioteca de tareas',
  },
  fr: {
    dashboard: 'Tableau de Bord', tasks: 'Tâches', weekly: 'Hebdomadaire', monthly: 'Mensuel', today: "Aujourd'hui",
    emailSync: 'Sync Email', addTask: '+ Ajouter Tâche', profile: 'Profil',
    logout: 'Déconnexion', changePassword: 'Changer le Mot de Passe', welcome: 'Bienvenue',
    yourTasks: 'Vos Tâches', noTasks: 'Pas encore de tâches', addNewTask: 'Ajouter Nouvelle Tâche',
    editTask: 'Modifier Tâche', title: 'Titre', description: 'Description',
    dueDate: "Date d'échéance", priority: 'Priorité', course: 'Cours',
    low: 'Basse', medium: 'Moyenne', high: 'Haute', save: 'Enregistrer', cancel: 'Annuler',
    delete: 'Supprimer', complete: 'Terminer', settings: 'Paramètres',
    language: 'Langue', aiAssistant: 'Assistant Étude IA',
    connectMicrosoft: 'Se connecter avec Microsoft', syncNow: 'Synchroniser',
    connected: 'Connecté', disconnected: 'Déconnecté',
    taskAdded: 'Tâche ajoutée!', taskUpdated: 'Tâche mise à jour!', taskDeleted: 'Tâche supprimée!',
    deleteConfirm: 'Voulez-vous supprimer cette tâche?',
    notifications: 'Notifications', noNotifications: 'Pas de notifications',
    markAllRead: 'Tout marquer comme lu', overdue: 'En retard', dueToday: "Aujourd'hui", dueTomorrow: 'Demain',
    completed: 'Terminé', pending: 'En cours', all: 'Tous', search: 'Rechercher',
    addFirstTask: 'Ajoutez votre première tâche!', focusMode: 'Mode Focus', startFocus: 'Démarrer Focus',
    pause: 'Pause', resume: 'Reprendre', reset: 'Réinitialiser', ready: 'Prêt', focusing: 'En focus', paused: 'En pause',
    sessionsToday: "Sessions aujourd'hui", generatingPlan: 'Génération de votre plan...', noPendingTasks: 'Pas de tâches en attente!',
    addTasksFromDashboard: 'Ajoutez des tâches depuis le Dashboard', loadingCalendar: 'Chargement du calendrier...',
    refresh: 'Actualiser', tasksPending: 'Tâches en attente', completedToday: "Terminées aujourd'hui",
    recommendedTaskOrder: 'Ordre recommandé', askMeAnything: 'Demandez-moi...',
    send: 'Envoyer', noLanguagesFound: 'Aucune langue trouvée', enterYourEmail: 'Votre email',
    enterPassword: 'Mot de passe', defaultDuration: '60', monthlyOverview: 'Vue Mensuelle',
    dashboardHomeSubtitle: "Votre centre de pilotage : l'essentiel du jour et des raccourcis.",
    statOverdue: 'En retard (ouvertes)',
    statDueToday: "Pour aujourd'hui",
    statHighPriority: 'Haute priorité (ouvertes)',
    statCompletedWeek: 'Terminées cette semaine',
    dashboardStatsAria: 'Statistiques des tâches',
    focusNextTasks: 'Prochaines cibles',
    focusNextTasksHint: 'Tâches ouvertes les plus urgentes.',
    focusEmpty: "Rien d'urgent. Ajoutez une tâche ou profitez d'une pause.",
    thisWeekWorkload: 'Cette semaine (planifiées)',
    workloadDaysWithTasks: 'Jours avec tâches',
    workloadOpenTasks: 'Tâches ouvertes',
    workloadEstTime: 'Temps est. (ouvertes)',
    hoursShort: 'h',
    minutesShort: 'm',
    filterActive: 'Actives',
    priorityAll: 'Toutes priorités',
    allCourses: 'Tous les cours',
    displayDensity: 'Densité de la liste',
    densityComfortable: 'Confort',
    densityCompact: 'Compact',
    tasksPageSubtitle: 'Recherchez, filtrez et gérez toutes vos tâches.',
    taskLibrary: 'Bibliothèque de tâches',
  },
  ar: {
    dashboard: 'لوحة التحكم', tasks: 'المهام', weekly: 'أسبوعي', monthly: 'شهري', today: 'اليوم',
    emailSync: 'مزامنة البريد', addTask: '+ إضافة مهمة', profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج', changePassword: 'تغيير كلمة المرور', welcome: 'مرحبا',
    yourTasks: 'مهامك', noTasks: 'لا توجد مهام بعد', addNewTask: 'إضافة مهمة جديدة',
    editTask: 'تعديل المهمة', title: 'العنوان', description: 'الوصف',
    dueDate: 'تاريخ الاستحقاق', priority: 'الأولوية', course: 'المقرر',
    low: 'منخفضة', medium: 'متوسطة', high: 'عالية', save: 'حفظ', cancel: 'إلغاء',
    delete: 'حذف', complete: 'إكمال', settings: 'الإعدادات',
    language: 'اللغة', aiAssistant: 'مساعد الدراسة الذكي',
    connectMicrosoft: 'تسجيل الدخول عبر Microsoft', syncNow: 'مزامنة الآن',
    connected: 'متصل', disconnected: 'غير متصل',
    taskAdded: 'تمت إضافة المهمة!', taskUpdated: 'تم تحديث المهمة!', taskDeleted: 'تم حذف المهمة!',
    deleteConfirm: 'هل أنت متأكد من حذف هذه المهمة؟',
    notifications: 'الإشعارات', noNotifications: 'لا توجد إشعارات',
    markAllRead: 'تحديد الكل كمقروء', overdue: 'متأخر', dueToday: 'اليوم', dueTomorrow: 'غدا',
    completed: 'مكتمل', pending: 'معلق', all: 'الكل', search: 'بحث',
    addFirstTask: 'أضف مهمتك الأولى!', focusMode: 'وضع التركيز', startFocus: 'بدء التركيز',
    pause: 'إيقاف مؤقت', resume: 'استئناف', reset: 'إعادة تعيين', ready: 'جاهز', focusing: ' التركيز', paused: 'متوقف',
    sessionsToday: 'جلسات اليوم', generatingPlan: 'جارٍ إنشاء خطتك...', noPendingTasks: 'لا توجد مهام معلقة!',
    addTasksFromDashboard: 'أضف مهام من لوحة التحكم', loadingCalendar: 'جارٍ تحميل التقويم...',
    refresh: 'تحديث', tasksPending: 'مهام معلقة', completedToday: 'مكتمل اليوم',
    recommendedTaskOrder: 'الترتيب الموصى به', noTasks: 'لا توجد مهام', askMeAnything: 'اسألني أي شيء...',
    send: 'إرسال', noLanguagesFound: 'لم يتم العثور على لغات', enterYourEmail: 'بريدك الإلكتروني',
    enterPassword: 'كلمة المرور', defaultDuration: '60',
  },
  de: {
    dashboard: 'Übersicht', tasks: 'Aufgaben', weekly: 'Woche', today: 'Heute',
    emailSync: 'E-Mail Sync', addTask: '+ Aufgabe hinzufügen', profile: 'Profil',
    logout: 'Abmelden', changePassword: 'Passwort ändern', welcome: 'Willkommen',
    yourTasks: 'Ihre Aufgaben', noTasks: 'Noch keine Aufgaben', addNewTask: 'Neue Aufgabe hinzufügen',
    editTask: 'Aufgabe bearbeiten', title: 'Titel', description: 'Beschreibung',
    dueDate: 'Fälligkeitsdatum', priority: 'Priorität', course: 'Kurs',
    low: 'Niedrig', medium: 'Mittel', high: 'Hoch', save: 'Speichern', cancel: 'Abbrechen',
    delete: 'Löschen', complete: 'Abschließen', settings: 'Einstellungen',
    language: 'Sprache', aiAssistant: 'KI Lernassistent',
    connectMicrosoft: 'Mit Microsoft anmelden', syncNow: 'Jetzt synchronisieren',
    connected: 'Verbunden', disconnected: 'Getrennt',
    taskAdded: 'Aufgabe hinzugefügt!', taskUpdated: 'Aufgabe aktualisiert!', taskDeleted: 'Aufgabe gelöscht!',
    deleteConfirm: 'Möchten Sie diese Aufgabe wirklich löschen?',
    notifications: 'Benachrichtigungen', noNotifications: 'Keine Benachrichtigungen',
    markAllRead: 'Alle als gelesen markieren', overdue: 'Überfällig', dueToday: 'Heute fällig', dueTomorrow: 'Morgen fällig',
    completed: 'Abgeschlossen', pending: 'Ausstehend', all: 'Alle', search: 'Suchen',
    addFirstTask: 'Fügen Sie Ihre erste Aufgabe hinzu!', focusMode: 'Fokus-Modus', startFocus: 'Fokus starten',
    pause: 'Pause', resume: 'Fortsetzen', reset: 'Zurücksetzen', ready: 'Bereit', focusing: 'Fokussiert', paused: 'Pausiert',
    sessionsToday: 'Sitzungen heute', generatingPlan: 'Plan wird erstellt...', noPendingTasks: 'Keine ausstehenden Aufgaben!',
    addTasksFromDashboard: 'Aufgaben vom Dashboard hinzufügen', loadingCalendar: 'Kalender wird geladen...',
    refresh: 'Aktualisieren', tasksPending: 'Ausstehende Aufgaben', completedToday: 'Heute abgeschlossen',
    recommendedTaskOrder: 'Empfohlene Reihenfolge', noTasks: 'Keine Aufgaben', askMeAnything: 'Frag mich alles...',
    send: 'Senden', noLanguagesFound: 'Keine Sprachen gefunden', enterYourEmail: 'Ihre E-Mail',
    enterPassword: 'Passwort', defaultDuration: '60',
  },
  zh: {
    dashboard: '仪表板', tasks: '任务', weekly: '每周', today: '今天',
    emailSync: '邮件同步', addTask: '+ 添加任务', profile: '个人资料',
    logout: '退出登录', changePassword: '更改密码', welcome: '欢迎',
    yourTasks: '您的任务', noTasks: '暂无任务', addNewTask: '添加新任务',
    editTask: '编辑任务', title: '标题', description: '描述',
    dueDate: '截止日期', priority: '优先级', course: '课程',
    low: '低', medium: '中', high: '高', save: '保存', cancel: '取消',
    delete: '删除', complete: '完成', settings: '设置',
    language: '语言', aiAssistant: 'AI学习助手',
    connectMicrosoft: '使用Microsoft登录', syncNow: '立即同步',
    connected: '已连接', disconnected: '未连接',
    taskAdded: '任务已添加！', taskUpdated: '任务已更新！', taskDeleted: '任务已删除！',
    deleteConfirm: '确定要删除此任务吗？',
    notifications: '通知', noNotifications: '暂无通知',
    markAllRead: '全部标为已读', overdue: '已逾期', dueToday: '今天到期', dueTomorrow: '明天到期',
    completed: '已完成', pending: '待处理', all: '全部', search: '搜索',
    addFirstTask: '添加您的第一个任务！', focusMode: '专注模式', startFocus: '开始专注',
    pause: '暂停', resume: '继续', reset: '重置', ready: '就绪', focusing: '专注中', paused: '已暂停',
    sessionsToday: '今日专注次数', generatingPlan: '正在生成您的计划...', noPendingTasks: '没有待处理任务！',
    addTasksFromDashboard: '从仪表板添加任务', loadingCalendar: '正在加载日历...',
    refresh: '刷新', tasksPending: '待处理任务', completedToday: '今日已完成',
    recommendedTaskOrder: '推荐顺序', noTasks: '暂无任务', askMeAnything: '问我任何问题...',
    send: '发送', noLanguagesFound: '未找到语言', enterYourEmail: '您的邮箱',
    enterPassword: '密码', defaultDuration: '60',
  },
  hi: {
    dashboard: 'डैशबोर्ड', tasks: 'कार्य', weekly: 'साप्ताहिक', today: 'आज',
    emailSync: 'ईमेल सिंक', addTask: '+ कार्य जोड़ें', profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट', changePassword: 'पासवर्ड बदलें', welcome: 'स्वागत है',
    yourTasks: 'आपके कार्य', noTasks: 'अभी तक कोई कार्य नहीं', addNewTask: 'नया कार्य जोड़ें',
    editTask: 'कार्य संपादित करें', title: 'शीर्षक', description: 'विवरण',
    dueDate: 'नियत तारीख', priority: 'प्राथमिकता', course: 'कोर्स',
    low: 'कम', medium: 'मध्यम', high: 'उच्च', save: 'सहेजें', cancel: 'रद्द करें',
    delete: 'हटाएं', complete: 'पूर्ण', settings: 'सेटिंग्स',
    language: 'भाषा', aiAssistant: 'AI अध्ययन सहायक',
    connectMicrosoft: 'Microsoft से कनेक्ट करें', syncNow: 'अभी सिंक करें',
    connected: 'कनेक्टेड', disconnected: 'डिस्कनेक्टेड',
    taskAdded: 'कार्य जोड़ा गया!', taskUpdated: 'कार्य अपडेट!', taskDeleted: 'कार्य हटाया गया!',
    deleteConfirm: 'क्या आप वाकई इस कार्य को हटाना चाहते हैं?',
    notifications: 'सूचनाएं', noNotifications: 'कोई सूचना नहीं',
    markAllRead: 'सभी पढ़े गए', overdue: 'अतिदेय', dueToday: 'आज देय', dueTomorrow: 'कल देय',
    completed: 'पूर्ण', pending: 'लंबित', all: 'सभी', search: 'खोजें',
    addFirstTask: 'अपना पहला कार्य जोड़ें!', focusMode: 'फोकस मोड', startFocus: 'फोकस शुरू करें',
    pause: 'रोकें', resume: 'जारी रखें', reset: 'रीसेट', ready: 'तैयार', focusing: 'फोकस', paused: 'रुका हुआ',
    sessionsToday: 'आज के सत्र', generatingPlan: 'आपकी योजना बना रहे हैं...', noPendingTasks: 'कोई लंबित कार्य नहीं!',
    addTasksFromDashboard: 'डैशबोर्ड से कार्य जोड़ें', loadingCalendar: 'कैलेंडर लोड हो रहा है...',
    refresh: 'रिफ्रेश', tasksPending: 'लंबित कार्य', completedToday: 'आज पूर्ण',
    recommendedTaskOrder: 'अनुशंसित क्रम', noTasks: 'कोई कार्य नहीं', askMeAnything: 'मुझसे कुछ भी पूछें...',
    send: 'भेजें', noLanguagesFound: 'कोई भाषा नहीं मिली', enterYourEmail: 'आपका ईमेल',
    enterPassword: 'पासवर्ड', defaultDuration: '60',
  },
  ta: {
    dashboard: 'டैஷ்போர்டு', tasks: 'பணிகள்', weekly: 'வாராந்திர', today: 'இன்று',
    emailSync: 'மின்னஞ்சல் ஒத்திசைவு', addTask: '+ பணி சேர்', profile: 'சுயவிவரம்',
    logout: 'வெளியேறு', changePassword: 'கடவுச்சொல் மாற்று', welcome: 'வரவேற்கிறோம்',
    yourTasks: 'உங்கள் பணிகள்', noTasks: 'பணிகள் இல்லை', addNewTask: 'புதிய பணி சேர்',
    editTask: 'பணி திருத்து', title: 'தலைப்பு', description: 'விளக்கம்',
    dueDate: 'இறுதி தேதி', priority: 'முன்னுரிமை', course: 'பாடம்',
    low: 'குறைந்த', medium: 'நடுத்தர', high: 'உயர்ந்த', save: 'சேமி', cancel: 'ரத்து',
    delete: 'நீக்கு', complete: 'முடித்தார்', settings: 'அமைப்புகள்',
    language: 'மொழி', aiAssistant: 'AI கற்றல் உதவியாளர்',
    connectMicrosoft: 'Microsoft உடன் உள்நுழைக', syncNow: 'இப்போது ஒத்திசைக்க',
    connected: 'இணைக்கப்பட்டது', disconnected: 'இணைக்கப்படவில்லை',
    taskAdded: 'பணி சேர்க்கப்பட்டது!', taskUpdated: 'பணி புதுப்பிக்கப்பட்டது!', taskDeleted: 'பணி நீக்கப்பட்டது!',
    deleteConfirm: 'இந்த பணியை நீக்க விரும்புகிறீர்களா?',
    notifications: 'அறிவிப்புகள்', noNotifications: 'அறிவிப்புகள் இல்லை',
    markAllRead: 'அனைத்தையும் படித்தது', overdue: 'தாமதம்', dueToday: 'இன்று', dueTomorrow: 'நாளை',
    completed: 'முடிந்தது', pending: 'நிலுவையில்', all: 'அனைத்தும்', search: 'தேடு',
    addFirstTask: 'உங்கள் முதல் பணியைச் சேர்க்க!', focusMode: 'கவனம் பயன்முறை', startFocus: 'கவனம் தொடங்க',
    pause: 'இடைநிறுத்து', resume: 'தொடர', reset: 'மீட்டமை', ready: 'தயார்', focusing: 'கவனம்', paused: 'நிறுத்தப்பட்டது',
    sessionsToday: 'இன்றைய அமர்வுகள்', generatingPlan: 'திட்டம் உருவாக்குகிறது...', noPendingTasks: 'நிலுவையில் பணிகள் இல்லை!',
    addTasksFromDashboard: 'டேஷ்போர்டிலிருந்து பணிகளைச் சேர்க்க', loadingCalendar: 'நாள்கTakvim加载...',
    refresh: 'புதுப்பி', tasksPending: 'நிலுவையில் பணிகள்', completedToday: 'இன்று முடித்தது',
    recommendedTaskOrder: 'பரிந்துரைக்கப்பட்ட வரிசை', noTasks: 'பணிகள் இல்லை', askMeAnything: 'எதையும் கேள்...',
    send: 'அனுப்பு', noLanguagesFound: 'மொழிகள் கிடைக்கவில்லை', enterYourEmail: 'உங்கள் மின்னஞ்சல்',
    enterPassword: 'கடவுச்சொல்', defaultDuration: '60',
  },
  te: {
    dashboard: 'डैशबोर्ड', tasks: 'কার్యালు', weekly: 'वार्षिक', today: 'ఈరోజు',
    emailSync: 'ఇమెయిల్ sync', addTask: '+ कार्यం చేర్చు', profile: 'প্রofil',
    logout: 'লాగ్ out', changePassword: 'password মిడ్', welcome: 'স্বागত',
    yourTasks: 'মী কার्य', noTasks: 'कार्य లేదు', addNewTask: 'క్ర new car',
    editTask: 'कार्य संपादित', title: 'शीर्षक', description: 'विवरण',
    dueDate: 'नियत तारीख', priority: 'प्राथमिकता', course: 'कोर्स',
    low: 'कम', medium: 'मध्यम', high: 'उच्च', save: 'save', cancel: 'रद्द',
    delete: 'हटाएं', complete: 'पूर्ण', settings: 'सेटिंग्स',
    language: 'भाषा', aiAssistant: 'AI learning assist',
    connectMicrosoft: 'Microsoft login', syncNow: 'sync now',
    connected: 'connected', disconnected: 'disconnected',
    taskAdded: 'কার্যం చేర్చబడింది!', taskUpdated: 'কার্যం अद्यतन!', taskDeleted: 'কার্যం deleted!',
    deleteConfirm: 'ఈ carयуд delete चाहते?',
    notifications: 'Notifications', noNotifications: 'No notifications',
    markAllRead: 'Mark all read', overdue: 'Overdue', dueToday: 'Due today', dueTomorrow: 'Due tomorrow',
    completed: 'Completed', pending: 'Pending', all: 'All', search: 'Search',
    addFirstTask: 'Add your first task!', focusMode: 'Focus Mode', startFocus: 'Start Focus',
    pause: 'Pause', resume: 'Resume', reset: 'Reset', ready: 'Ready', focusing: 'Focusing', paused: 'Paused',
    sessionsToday: 'Sessions today', generatingPlan: 'Generating plan...', noPendingTasks: 'No pending!',
    addTasksFromDashboard: 'Add from dashboard', loadingCalendar: 'Loading...',
    refresh: 'Refresh', tasksPending: 'Pending', completedToday: 'Done today',
    recommendedTaskOrder: 'Recommended', noTasks: 'No tasks', askMeAnything: 'Ask me...',
    send: 'Send', noLanguagesFound: 'No found', enterYourEmail: 'Your email',
    enterPassword: 'Password', defaultDuration: '60',
  },
  mr: {
    dashboard: 'डॅशबोर्ड', tasks: 'कार्ये', weekly: 'साप्ताहिक', today: 'आज',
    emailSync: 'ईमेल सिंक', addTask: '+ कार्य जोडा', profile: 'प्रोफाइल',
    logout: 'लॉग आउट', changePassword: 'पासवर्ड बदला', welcome: 'स्वागत आहे',
    yourTasks: 'तुमची कार्ये', noTasks: 'अद्याप कार्य नाहीत', addNewTask: 'नवीन कार्य जोडा',
    editTask: 'कार्य संपादित करा', title: 'शीर्षक', description: 'वर्णन',
    dueDate: 'शेवटची तारीख', priority: 'प्राधान्य', course: 'कोर्स',
    low: 'कम', medium: 'मध्यम', high: 'उच्च', save: 'जतन करा', cancel: 'रद्द करा',
    delete: 'हटवा', complete: 'पूर्ण', settings: 'सेटिंग्ज',
    language: 'भाषा', aiAssistant: 'AI अभ्यास सहायक',
    connectMicrosoft: 'Microsoft ने लॉगिन करा', syncNow: 'आता सिंक करा',
    connected: 'जोडलेले', disconnected: 'डिस्कनेक्टेड',
    taskAdded: 'कार्य जोडले!', taskUpdated: 'कार्य अपडेट!', taskDeleted: 'कार्य हटवले!',
    deleteConfirm: 'हे कार्य हटवणे?',
    notifications: 'सूचना', noNotifications: 'सूचना नाही',
    markAllRead: 'सर्व वाचले', overdue: 'उशीर', dueToday: 'आज', dueTomorrow: 'उद्या',
    completed: 'पूर्ण', pending: 'प्रलंबित', all: 'सर्व', search: 'शोध',
    addFirstTask: 'पहिला कार्य जोडा!', focusMode: 'फोकस मोड', startFocus: 'फोकस सुरू',
    pause: 'थांबा', resume: 'पुन्हा', reset: 'रीसेट', ready: 'तयार', focusing: 'फोकस', paused: 'थांबले',
    sessionsToday: 'आजचे सत्र', generatingPlan: 'योजना तयार...', noPendingTasks: 'काम नाही!',
    addTasksFromDashboard: 'Dashboard वरून जोडा', loadingCalendar: 'लोड होत...',
    refresh: 'रिफ्रेश', tasksPending: 'प्रलंबित', completedToday: 'आज पूर्ण',
    recommendedTaskOrder: 'शिफारस', noTasks: 'काम नाही', askMeAnything: 'विश्वास...',
    send: 'पाठवा', noLanguagesFound: 'भाषा नाही', enterYourEmail: 'ईमेल',
    enterPassword: 'पासवर्ड', defaultDuration: '60',
  },
  gu: {
    dashboard: 'ડૅશબોર્ડ', tasks: 'કામ', weekly: 'સાપ્તાહિક', today: 'આજ',
    emailSync: 'ઈમેલ સિંક', addTask: '+ કામ ઉમેરો', profile: 'પ્રોફાઈલ',
    logout: 'લોગ આઉટ', changePassword: 'પાસવર્ડ બદલો', welcome: 'સ્વાગત છે',
    yourTasks: 'તમારા કામ', noTasks: 'હજુ કોઈ કામ નથી', addNewTask: 'નવું કામ ઉમેરો',
    editTask: 'કામ સંપાદિત કરો', title: 'શીર્ષક', description: 'વર્ણન',
    dueDate: 'અંતિમ તારીખ', priority: 'પ્રાથમિકતા', course: 'અભ્યાસ',
    low: 'નીચું', medium: 'મધ્યમ', high: 'ઉચ્ચ', save: 'સંગ્રહ', cancel: 'રદ',
    delete: 'હટાવો', complete: 'પૂર્ણ', settings: 'સેટિંગ્સ',
    language: 'ભાષા', aiAssistant: 'AI અભ્યાસ સહાયક',
    connectMicrosoft: 'Microsoft થી લોગિન', syncNow: 'હવે સિંક',
    connected: 'જોડાયેલ', disconnected: 'ડિસ્કનેક્ટેડ',
    taskAdded: 'કામ ઉમેરાયું!', taskUpdated: 'કામ અપડેટ!', taskDeleted: 'કામ deleted!',
    deleteConfirm: 'આ કામ delete?',
    notifications: 'Notifications', noNotifications: 'No notifications',
    markAllRead: 'Mark all read', overdue: 'Overdue', dueToday: 'Due today', dueTomorrow: 'Due tomorrow',
    completed: 'Completed', pending: 'Pending', all: 'All', search: 'Search',
    addFirstTask: 'Add first!', focusMode: 'Focus Mode', startFocus: 'Start',
    pause: 'Pause', resume: 'Resume', reset: 'Reset', ready: 'Ready', focusing: 'Focusing', paused: 'Paused',
    sessionsToday: 'Sessions today', generatingPlan: 'Generating...', noPendingTasks: 'No pending!',
    addTasksFromDashboard: 'Add from dashboard', loadingCalendar: 'Loading...',
    refresh: 'Refresh', tasksPending: 'Pending', completedToday: 'Done today',
    recommendedTaskOrder: 'Recommended', noTasks: 'No tasks', askMeAnything: 'Ask...',
    send: 'Send', noLanguagesFound: 'No found', enterYourEmail: 'Your email',
    enterPassword: 'Password', defaultDuration: '60',
  },
  te: {
    dashboard: 'डैशबोर्ड', tasks: 'కార్యాలు', weekly: 'वार्षिक', today: 'ఈరోజు',
    emailSync: 'ఇమెయిల్ sync', addTask: '+ కార్యం చేర్చు', profile: 'ప్రofil',
    logout: 'లాగ్ out', changePassword: 'password मिड', welcome: 'स्वागत',
    yourTasks: 'మీ कार्य', noTasks: 'कार्य लागू', addNewTask: 'क نو कार्य',
    editTask: 'कार्य संपादित', title: 'शीर्षक', description: 'विवरण',
    dueDate: 'नियत तारीख', priority: 'प्राथमिकता', course: 'कोर्स',
    low: 'कम', medium: 'मध्यम', high: 'उच्च', save: 'save', cancel: 'रद्द',
    delete: 'हटाएं', complete: 'पूर्ण', settings: 'सेटिंग्स',
    language: 'भाषा', aiAssistant: 'AI learning assist',
    connectMicrosoft: 'Microsoft login', syncNow: 'sync now',
    connected: 'connected', disconnected: 'disconnected',
  },
  mr: {
    dashboard: 'डॅशबोर्ड', tasks: 'कार्ये', weekly: 'साप्ताहिक', today: 'आज',
    emailSync: 'ईमेल सिंक', addTask: '+ कार्य जोडा', profile: 'प्रोफाइल',
    logout: 'लॉग आउट', changePassword: 'पासवर्ड बदला', welcome: 'स्वागत आहे',
    yourTasks: 'तुमची कार्ये', noTasks: 'अद्याप कार्य नाहीत', addNewTask: 'नवीन कार्य जोडा',
    editTask: 'कार्य संपादित करा', title: 'शीर्षक', description: 'वर्णन',
    dueDate: 'शेवटची तारीख', priority: 'प्राधान्य', course: 'कोर्स',
    low: 'कम', medium: 'मध्यम', high: 'उच्च', save: 'जतन करा', cancel: 'रद्द करा',
    delete: 'हटवा', complete: 'पूर्ण', settings: 'सेटिंग्ज',
    language: 'भाषा', aiAssistant: 'AI अभ्यास सहायक',
    connectMicrosoft: 'Microsoft ने लॉगिन करा', syncNow: 'आता सिंक करा',
    connected: 'जोडलेले', disconnected: 'डिस्कनेक्टेड',
  },
  gu: {
    dashboard: 'ડૅશબોર્ડ', tasks: 'કામ', weekly: 'સાપ્તાહિક', today: 'આજ',
    emailSync: 'ઈમેલ સિંક', addTask: '+ કામ ઉમેરો', profile: 'પ્રોફાઈલ',
    logout: 'લોગ આઉટ', changePassword: 'પાસવર્ડ બદલો', welcome: 'સ્વાગત છે',
    yourTasks: 'તમારા કામ', noTasks: 'હજુ કોઈ કામ નથી', addNewTask: 'નવું કામ ઉમેરો',
    editTask: 'કામ સંપાદિત કરો', title: 'શીર્ષક', description: 'વર્ણન',
    dueDate: 'અંતિમ તારીખ', priority: 'પ્રાથમિકતા', course: 'અભ્યાસ',
    low: 'નીચું', medium: 'મધ્યમ', high: 'ઉચ્ચ', save: 'સંગ્રહ', cancel: 'રદ',
    delete: 'હટાવો', complete: 'પૂર્ણ', settings: 'સેટિંગ્સ',
    language: 'ભાષા', aiAssistant: 'AI અભ્યાસ સહાયક',
    connectMicrosoft: 'Microsoft થી લોગિન', syncNow: 'હવે સિંક',
    connected: 'જોડાયેલ', disconnected: 'ડિસ્કનેક્ટેડ',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', tasks: 'ಕಾರ್ಯಗಳು', weekly: 'ವಾರದ', today: 'ಇಂದು',
    emailSync: 'ಇಮೇಲ್ ಸಿಂಕ್', addTask: '+ ಕಾರ್ಯ ಸೇರಿಸಿ', profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್‌ಔಟ್', changePassword: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ', welcome: 'ಸ್ವಾಗತ',
    yourTasks: 'ನಿಮ್ಮ ಕಾರ್ಯಗಳು', noTasks: 'ಇನ್ನೂ ಕಾರ್ಯಗಳಿಲ್ಲ', addNewTask: 'ಹೊಸ ಕಾರ್ಯ ಸೇರಿಸಿ',
    editTask: 'ಕಾರ್ಯ ಸಂಪಾದಿಸಿ', title: 'ಶೀರ್ಷಿಕೆ', description: 'ವಿವರಣೆ',
    dueDate: 'ಗಡುವು', priority: 'ಆದ್ಯತೆ', course: 'ಕೋರ್ಸ್',
    low: 'ಕಡಿಮೆ', medium: 'ಮಧ್ಯಮ', high: 'ಎತ್ತರ', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದು',
    delete: 'ತೆಗೆದುಹಾಕಿ', complete: 'ಮುಗಿಸಿ', settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    language: 'ಭಾಷೆ', aiAssistant: 'AI ಕಲಿಕಾ ಸಹಾಯಕ',
    connectMicrosoft: 'Microsoft ನಿಂದ ಲಾಗಿನ್', syncNow: 'ಈಗ ಸಿಂಕ್',
    connected: 'ಸಂಪರ್ಕಿಸಲಾಗಿದೆ', disconnected: 'ಸಂಪರ್ಕಿಸಲಾಗಿಲ್ಲ',
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോര്‍ഡ്', tasks: 'ജോലികള്‍', weekly: 'ആഴ്ചതോരമായ', today: 'ഇന്ന്',
    emailSync: 'ഇമെയില്‍ സിങ്ക്', addTask: '+ ജോലി ചേര്‍ക്കുക', profile: 'പ്രൊഫൈല്‍',
    logout: 'ലോഗ്‌ഔട്ട്', changePassword: 'പാസ്‌വേര്‍ഡ് മാറ്റുക', welcome: 'സ്വാഗതം',
    yourTasks: 'നിങ്ങളുടെ ജോലികള്‍', noTasks: 'ഇതുവരെ ജോലികളില്ല', addNewTask: 'പുതിയ ജോലി ചേര്‍ക്കുക',
    editTask: 'ജോലി തിരുത്തുക', title: 'ശീര്‍ഷകം', description: 'വിവരണം',
    dueDate: 'അവസാന തിയതി', priority: 'മുന്‍ഗണന', course: 'കോഴ്സ്',
    low: 'കുറവ്', medium: 'ഇടത്തരം', high: 'ഉയര്‍ന്ന', save: 'സംരക്ഷിക്കുക', cancel: 'റദ്ദാക്കുക',
    delete: 'നീക്കം ചെയ്യുക', complete: 'പൂര്‍ത്തിയാക്കുക', settings: 'സെറ്റിംഗ്സ്',
    language: 'ഭാഷ', aiAssistant: 'AI പഠന സഹായി',
    connectMicrosoft: 'Microsoft വഴി ലോഗിന്‍', syncNow: 'ഇപ്പോള്‍ സിങ്ക് ചെയ്യുക',
    connected: 'ബന്ധിപ്പിച്ചിരിക്കുന്ന', disconnected: 'ബന്ധിപ്പിച്ചിട്ടില്ല',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ', tasks: 'ਕੰਮ', weekly: 'ਹਫ਼ਤਾਵਾਰੀ', today: 'ਅੱਜ',
    emailSync: 'ਈਮੇਲ ਸਿੰਕ', addTask: '+ ਕੰਮ ਜੋਡੋ', profile: 'ਪ੍ਰੋਫ਼ਾਈਲ',
    logout: 'ਲਾਗ ਆਊਟ', changePassword: 'ਪਾਸਵਰਡ ਬਦਲੋ', welcome: 'ਸਵਾਗਤ',
    yourTasks: 'ਤੁਹਾਡੇ ਕੰਮ', noTasks: 'ਹੋਰ ਕੋਈ ਕੰਮ ਨਹੀਂ', addNewTask: 'ਨਵਾਂ ਕੰਮ ਜੋਡੋ',
    editTask: 'ਕੰਮ ਸੰਪਾਦਿਤ ਕਰੋ', title: 'ਸਿਰਲੇਖ', description: 'ਵਰਣਨ',
    dueDate: 'ਅੰਤਿਮ ਤਾਰੀਖ', priority: 'ਤਰਜੀਹ', course: 'ਕੋਰਸ',
    low: 'ਘੱਟ', medium: 'ਵਿਚਕਾਰਲਾ', high: 'ਉੱਚਾ', save: 'ਸੇਵ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ',
    delete: 'ਹਟਾਓ', complete: 'ਪੂਰਾ ਕਰੋ', settings: 'ਸੈਟਿੰਗਸ',
    language: 'ਭਾਸ਼ਾ', aiAssistant: 'AI ਅਧਿਐਨ ਸਹਾਇਕ',
    connectMicrosoft: 'Microsoft ਨਾਲ ਲਾਗਿਨ', syncNow: 'ਹੁਣ ਸਿੰਕ ਕਰੋ',
    connected: 'ਕੁਨੈਕਟਿਡ', disconnected: 'ਡਿਸਕੁਨੈਕਟਿਡ',
  },
  or: {
    dashboard: 'ଡ୍ୟାଶବୋର୍ଡ', tasks: 'କାମ', weekly: 'ସାପ୍ତାହିକ', today: 'ଆଜ',
    emailSync: 'ଇମେଲ ସିଙ୍କ', addTask: '+ କାମ ଯୋଡ଼ିବେ', profile: 'ପ୍ରୋଫାଇଲ',
    logout: 'ଲଗଆଉଟ', changePassword: 'ପାସୱର୍ଡ ବଦଲାବେ', welcome: 'ସ୍ୱାଗତ',
    yourTasks: 'ତୁମର କାମ', noTasks: 'କୌଣସି କାମ ନାਹିଁ', addNewTask: 'ନୂତନ କାମ ଯୋଡ଼ିବେ',
    editTask: 'କାମ ସଂପାଦିତ କରୁଥିବେ', title: 'ଶୀର୍ଷକ', description: 'ବିବରଣୀ',
    dueDate: 'ଶେ਷ ତାਰੀਖ', priority: 'ପ୍ਰਾਥਮਿਕতਾ', course: 'କୋਰਸ',
    low: 'କମ', medium: 'ମଧ୍ਯਮ', high: 'ଉଚ୍ਚ', save: 'ସେਵ କਰੁ', cancel: 'ରଦ କਰୁ',
    delete: 'ହଟାବେ', complete: 'ସମ୍ਪੂਰ୍ਣ', settings: 'ସେਟਿੰਗਸ',
    language: 'ଭାଷਾ', aiAssistant: 'AI ଅଧ୍ਯୟਨ ସਹਾਇਕ',
    connectMicrosoft: 'Microsoft ସହ ଲଗଇਨ', syncNow: 'ଏବେ ସਿଙ୍କ କਰୁ',
    connected: 'ସଂਯੁਕਤ', disconnected: 'ଡਿਸਕੁਨੈਕਟਿਡ',
  },
  as: {
    dashboard: 'ডেশবোৰ্ড', tasks: 'কাম', weekly: 'সাপ্তাহিক', today: 'আজি',
    emailSync: 'ইমেইল চিঙ্ক', addTask: '+ কাম যোগ কৰক', profile: 'প্রফাইল',
    logout: 'লগ আউট', changePassword: 'পাছৱার্ড সলাও', welcome: 'স্বাগতম',
    yourTasks: 'আপোনাৰ কাম', noTasks: 'এতিয়াও কাম নাই', addNewTask: 'নতুন কাম যোগ কৰক',
    editTask: 'কাম সম্পাদনা কৰক', title: 'শীর্ষক', description: 'বিৱৰণ',
    dueDate: 'শেষ তাৰিখ', priority: 'প্রাধান্য', course: 'কোর্স',
    low: 'কম', medium: 'মধ্যম', high: 'উচ্চ', save: 'সংৰক্ষণ', cancel: 'বাতিল',
    delete: 'মচি দে', complete: 'সম্পূর্ণ', settings: 'ছেটিংছ',
    language: 'ভাষা', aiAssistant: 'AI অধ্যয়ন সহায়ক',
    connectMicrosoft: 'Microsoft ৰ মাধ্যমে লগ ইন', syncNow: 'এতিয়া চিঙ্ক কৰক',
    connected: 'সংযুক্ত', disconnected: 'বিচ্ছিন্ন',
  },
  ur: {
    dashboard: 'ڈیش بورڈ', tasks: 'کام', weekly: 'ہفتہ وار', today: 'آج',
    emailSync: 'ای میل سینک', addTask: '+ کام شامل کریں', profile: 'پروفائل',
    logout: 'لاگ آؤٹ', changePassword: 'پاسورڈ تبدیل کریں', welcome: 'خوش آمدید',
    yourTasks: 'آپ کے کام', noTasks: 'کوئی کام نہیں', addNewTask: 'نیا کام شامل کریں',
    editTask: 'کام ترمیم کریں', title: 'عنوان', description: 'تفصیل',
    dueDate: 'آخری تاریخ', priority: 'ترجیح', course: 'کورس',
    low: 'کم', medium: 'درمیانہ', high: 'اعلی', save: 'محفوظ کریں', cancel: 'منسوخ',
    delete: 'حذف کریں', complete: 'مکمل', settings: 'ترتیبات',
    language: 'زبان', aiAssistant: 'AI اسٹڈی اسسٹنٹ',
    connectMicrosoft: 'Microsoft سے لاگ ان کریں', syncNow: 'اب سینک کریں',
    connected: 'مقبول', disconnected: 'غیر متصل',
  },
  pt: {
    dashboard: 'Painel', tasks: 'Tarefas', weekly: 'Semanal', today: 'Hoje',
    emailSync: 'Sincronizar Email', addTask: '+ Adicionar Tarefa', profile: 'Perfil',
    logout: 'Sair', changePassword: 'Alterar Senha', welcome: 'Bem-vindo',
    yourTasks: 'Suas Tarefas', noTasks: 'Nenhuma tarefa ainda', addNewTask: 'Adicionar Nova Tarefa',
    editTask: 'Editar Tarefa', title: 'Título', description: 'Descrição',
    dueDate: 'Data de Vencimento', priority: 'Prioridade', course: 'Curso',
    low: 'Baixa', medium: 'Média', high: 'Alta', save: 'Salvar', cancel: 'Cancelar',
    delete: 'Excluir', complete: 'Concluir', settings: 'Configurações',
    language: 'Idioma', aiAssistant: 'Assistente de Estudo IA',
    connectMicrosoft: 'Entrar com Microsoft', syncNow: 'Sincronizar Agora',
    connected: 'Conectado', disconnected: 'Desconectado',
  },
  ja: {
    dashboard: 'ダッシュボード', tasks: 'タスク', weekly: '毎週', today: '今日',
    emailSync: 'メール同期', addTask: '+ タスクを追加', profile: 'プロフィール',
    logout: 'ログアウト', changePassword: 'パスワードを変更', welcome: 'ようこそ',
    yourTasks: 'あなたのタスク', noTasks: 'タスクはまだありません', addNewTask: '新しいタスクを追加',
    editTask: 'タスクを編集', title: 'タイトル', description: '説明',
    dueDate: '期限', priority: '優先度', course: 'コース',
    low: '低', medium: '中', high: '高', save: '保存', cancel: 'キャンセル',
    delete: '削除', complete: '完了', settings: '設定',
    language: '言語', aiAssistant: 'AI学習アシスタント',
    connectMicrosoft: 'Microsoftでサインイン', syncNow: '今すぐ同期',
    connected: '接続済み', disconnected: '未接続',
  },
  ko: {
    dashboard: '대시보드', tasks: '작업', weekly: '주간', today: '오늘',
    emailSync: '이메일 동기화', addTask: '+ 작업 추가', profile: '프로필',
    logout: '로그아웃', changePassword: '비밀번호 변경', welcome: '환영합니다',
    yourTasks: '내 작업', noTasks: '아직 작업이 없습니다', addNewTask: '새 작업 추가',
    editTask: '작업 편집', title: '제목', description: '설명',
    dueDate: '마감일', priority: '우선순위', course: '강좌',
    low: '낮음', medium: '중간', high: '높음', save: '저장', cancel: '취소',
    delete: '삭제', complete: '완료', settings: '설정',
    language: '언어', aiAssistant: 'AI 학습 도우미',
    connectMicrosoft: 'Microsoft로 로그인', syncNow: '지금 동기화',
    connected: '연결됨', disconnected: '연결 안됨',
  },
  ru: {
    dashboard: 'Панель', tasks: 'Задачи', weekly: 'Неделя', today: 'Сегодня',
    emailSync: 'Синхронизация почты', addTask: '+ Добавить задачу', profile: 'Профиль',
    logout: 'Выйти', changePassword: 'Изменить пароль', welcome: 'Добро пожаловать',
    yourTasks: 'Ваши задачи', noTasks: 'Пока нет задач', addNewTask: 'Добавить новую задачу',
    editTask: 'Редактировать задачу', title: 'Название', description: 'Описание',
    dueDate: 'Срок', priority: 'Приоритет', course: 'Курс',
    low: 'Низкий', medium: 'Средний', high: 'Высокий', save: 'Сохранить', cancel: 'Отмена',
    delete: 'Удалить', complete: 'Завершить', settings: 'Настройки',
    language: 'Язык', aiAssistant: 'AI Помощник по учебе',
    connectMicrosoft: 'Войти через Microsoft', syncNow: 'Синхронизировать',
    connected: 'Подключено', disconnected: 'Отключено',
  },
  it: {
    dashboard: 'Dashboard', tasks: 'Attività', weekly: 'Settimanale', today: 'Oggi',
    emailSync: 'Sincronizza Email', addTask: '+ Aggiungi Attività', profile: 'Profilo',
    logout: 'Esci', changePassword: 'Cambia Password', welcome: 'Benvenuto',
    yourTasks: 'Le tue attività', noTasks: 'Nessuna attività ancora', addNewTask: 'Aggiungi Nuova Attività',
    editTask: 'Modifica Attività', title: 'Titolo', description: 'Descrizione',
    dueDate: 'Data di scadenza', priority: 'Priorità', course: 'Corso',
    low: 'Bassa', medium: 'Media', high: 'Alta', save: 'Salva', cancel: 'Annulla',
    delete: 'Elimina', complete: 'Completa', settings: 'Impostazioni',
    language: 'Lingua', aiAssistant: 'Assistente Studio AI',
    connectMicrosoft: 'Accedi con Microsoft', syncNow: 'Sincronizza Ora',
    connected: 'Connesso', disconnected: 'Disconnesso',
  },
  tr: {
    dashboard: 'Panel', tasks: 'Görevler', weekly: 'Haftalık', today: 'Bugün',
    emailSync: 'E-posta Senkronizasyonu', addTask: '+ Görev Ekle', profile: 'Profil',
    logout: 'Çıkış Yap', changePassword: 'Parola Değiştir', welcome: 'Hoş geldiniz',
    yourTasks: 'Görevleriniz', noTasks: 'Henüz görev yok', addNewTask: 'Yeni Görev Ekle',
    editTask: 'Görevi Düzenle', title: 'Başlık', description: 'Açıklama',
    dueDate: 'Bitiş Tarihi', priority: 'Öncelik', course: 'Ders',
    low: 'Düşük', medium: 'Orta', high: 'Yüksek', save: 'Kaydet', cancel: 'İptal',
    delete: 'Sil', complete: 'Tamamla', settings: 'Ayarlar',
    language: 'Dil', aiAssistant: 'AI Çalışma Asistanı',
    connectMicrosoft: 'Microsoft ile giriş yap', syncNow: 'Şimdi Senkronize Et',
    connected: 'Bağlı', disconnected: 'Bağlı değil',
  },
  nl: {
    dashboard: 'Dashboard', tasks: 'Taken', weekly: 'Wekelijks', today: 'Vandaag',
    emailSync: 'E-mail synchronisatie', addTask: '+ Taak toevoegen', profile: 'Profiel',
    logout: 'Uitloggen', changePassword: 'Wachtwoord wijzigen', welcome: 'Welkom',
    yourTasks: 'Jouw taken', noTasks: 'Nog geen taken', addNewTask: 'Nieuwe taak toevoegen',
    editTask: 'Taak bewerken', title: 'Titel', description: 'Beschrijving',
    dueDate: 'Vervaldatum', priority: 'Prioriteit', course: 'Cursus',
    low: 'Laag', medium: 'Medium', high: 'Hoog', save: 'Opslaan', cancel: 'Annuleren',
    delete: 'Verwijderen', complete: 'Voltooien', settings: 'Instellingen',
    language: 'Taal', aiAssistant: 'AI Studie Assistent',
    connectMicrosoft: 'Aanmelden met Microsoft', syncNow: 'Nu synchroniseren',
    connected: 'Verbonden', disconnected: 'Niet verbonden',
  },
  pl: {
    dashboard: 'Pulpit', tasks: 'Zadania', weekly: 'Tygodniowy', today: 'Dzisiaj',
    emailSync: 'Synchronizacja e-mail', addTask: '+ Dodaj zadanie', profile: 'Profil',
    logout: 'Wyloguj', changePassword: 'Zmień hasło', welcome: 'Witaj',
    yourTasks: 'Twoje zadania', noTasks: 'Brak zadań', addNewTask: 'Dodaj nowe zadanie',
    editTask: 'Edytuj zadanie', title: 'Tytuł', description: 'Opis',
    dueDate: 'Termin', priority: 'Priorytet', course: 'Kurs',
    low: 'Niski', medium: 'Średni', high: 'Wysoki', save: 'Zapisz', cancel: 'Anuluj',
    delete: 'Usuń', complete: 'Zakończ', settings: 'Ustawienia',
    language: 'Język', aiAssistant: 'AI Asystent nauki',
    connectMicrosoft: 'Zaloguj się przez Microsoft', syncNow: 'Synchronizuj teraz',
    connected: 'Połączony', disconnected: 'Rozłączony',
  },
  sv: {
    dashboard: 'Instrumentpanel', tasks: 'Uppgifter', weekly: 'Veckovis', today: 'Idag',
    emailSync: 'E-postsynkronisering', addTask: '+ Lägg till uppgift', profile: 'Profil',
    logout: 'Logga ut', changePassword: 'Ändra lösenord', welcome: 'Välkommen',
    yourTasks: 'Dina uppgifter', noTasks: 'Inga uppgifter än', addNewTask: 'Lägg till ny uppgift',
    editTask: 'Redigera uppgift', title: 'Titel', description: 'Beskrivning',
    dueDate: 'Förfallodag', priority: 'Prioritet', course: 'Kurs',
    low: 'Låg', medium: 'Medel', high: 'Hög', save: 'Spara', cancel: 'Avbryt',
    delete: 'Ta bort', complete: 'Slutför', settings: 'Inställningar',
    language: 'Språk', aiAssistant: 'AI Studieassistent',
    connectMicrosoft: 'Logga in med Microsoft', syncNow: 'Synkronisera nu',
    connected: 'Ansluten', disconnected: 'Frånkopplad',
  },
  da: {
    dashboard: 'Dashboard', tasks: 'Opgaver', weekly: 'Ugentlig', today: 'I dag',
    emailSync: 'E-mail synkronisering', addTask: '+ Tilføj opgave', profile: 'Profil',
    logout: 'Log ud', changePassword: 'Skift adgangskode', welcome: 'Velkommen',
    yourTasks: 'Dine opgaver', noTasks: 'Ingen opgaver endnu', addNewTask: 'Tilføj ny opgave',
    editTask: 'Rediger opgave', title: 'Titel', description: 'Beskrivelse',
    dueDate: 'Forfaldsdag', priority: 'Prioritet', course: 'Kursus',
    low: 'Lav', medium: 'Medium', high: 'Høj', save: 'Gem', cancel: 'Annuller',
    delete: 'Slet', complete: 'Færdig', settings: 'Indstillinger',
    language: 'Sprog', aiAssistant: 'AI Studieassistent',
    connectMicrosoft: 'Log ind med Microsoft', syncNow: 'Synkroniser nu',
    connected: 'Tilsluttet', disconnected: 'Frakoblet',
  },
  no: {
    dashboard: 'Dashbord', tasks: 'Oppgaver', weekly: 'Ukentlig', today: 'I dag',
    emailSync: 'E-post synkronisering', addTask: '+ Legg til oppgave', profile: 'Profil',
    logout: 'Logg ut', changePassword: 'Endre passord', welcome: 'Velkommen',
    yourTasks: 'Dine oppgaver', noTasks: 'Ingen oppgaver ennå', addNewTask: 'Legg til ny oppgave',
    editTask: 'Rediger oppgave', title: 'Tittel', description: 'Beskrivelse',
    dueDate: 'Forfallsdato', priority: 'Prioritet', course: 'Kurs',
    low: 'Lav', medium: 'Medium', high: 'Høy', save: 'Lagre', cancel: 'Avbryt',
    delete: 'Slett', complete: 'Fullfør', settings: 'Innstillinger',
    language: 'Språk', aiAssistant: 'AI Studieassistent',
    connectMicrosoft: 'Logg inn med Microsoft', syncNow: 'Synkroniser nå',
    connected: 'Tilkoblet', disconnected: 'Frakoblet',
  },
  fi: {
    dashboard: 'Kojelauta', tasks: 'Tehtävät', weekly: 'Viikottain', today: 'Tänään',
    emailSync: 'Sähköpostin synkronointi', addTask: '+ Lisää tehtävä', profile: 'Profiili',
    logout: 'Kirjaudu ulos', changePassword: 'Vaihda salasana', welcome: 'Tervetuloa',
    yourTasks: 'Tehtäväsi', noTasks: 'Ei vielä tehtäviä', addNewTask: 'Lisää uusi tehtävä',
    editTask: 'Muokkaa tehtävää', title: 'Otsikko', description: 'Kuvaus',
    dueDate: 'Eräpäivä', priority: 'Prioriteetti', course: 'Kurssi',
    low: 'Matala', medium: 'Keskitaso', high: 'Korkea', save: 'Tallenna', cancel: 'Peruuta',
    delete: 'Poista', complete: 'Valmis', settings: 'Asetukset',
    language: 'Kieli', aiAssistant: 'AI Opiskeluavustaja',
    connectMicrosoft: 'Kirjaudu Microsoftilla', syncNow: 'Synkronoi nyt',
    connected: 'Yhdistetty', disconnected: 'Ei yhdistetty',
  },
  th: {
    dashboard: 'แดชบอร์ด', tasks: 'งาน', weekly: 'รายสัปดาห์', today: 'วันนี้',
    emailSync: 'ซิงโครไนซ์อีเมล', addTask: '+ เพิ่มงาน', profile: 'โปรไฟล์',
    logout: 'ออกจากระบบ', changePassword: 'เปลี่ยนรหัสผ่าน', welcome: 'ยินดีต้อนรับ',
    yourTasks: 'งานของคุณ', noTasks: 'ยังไม่มีงาน', addNewTask: 'เพิ่มงานใหม่',
    editTask: 'แก้ไขงาน', title: 'หัวข้อ', description: 'รายละเอียด',
    dueDate: 'กำหนดส่ง', priority: 'ลำดับความสำคัญ', course: 'วิชา',
    low: 'ต่ำ', medium: 'ปานกลาง', high: 'สูง', save: 'บันทึก', cancel: 'ยกเลิก',
    delete: 'ลบ', complete: 'เสร็จสิ้น', settings: 'การตั้งค่า',
    language: 'ภาษา', aiAssistant: 'ผู้ช่วย AI การเรียน',
    connectMicrosoft: 'เข้าสู่ระบบด้วย Microsoft', syncNow: 'ซิงโครไนซ์ตอนนี้',
    connected: 'เชื่อมต่อแล้ว', disconnected: 'ไม่ได้เชื่อมต่อ',
  },
  vi: {
    dashboard: 'Bảng điều khiển', tasks: 'Công việc', weekly: 'Hàng tuần', today: 'Hôm nay',
    emailSync: 'Đồng bộ email', addTask: '+ Thêm công việc', profile: 'Hồ sơ',
    logout: 'Đăng xuất', changePassword: 'Đổi mật khẩu', welcome: 'Chào mừng',
    yourTasks: 'Công việc của bạn', noTasks: 'Chưa có công việc', addNewTask: 'Thêm công việc mới',
    editTask: 'Sửa công việc', title: 'Tiêu đề', description: 'Mô tả',
    dueDate: 'Ngày đến hạn', priority: 'Ưu tiên', course: 'Khóa học',
    low: 'Thấp', medium: 'Trung bình', high: 'Cao', save: 'Lưu', cancel: 'Hủy',
    delete: 'Xóa', complete: 'Hoàn thành', settings: 'Cài đặt',
    language: 'Ngôn ngữ', aiAssistant: 'Trợ lý AI học tập',
    connectMicrosoft: 'Đăng nhập bằng Microsoft', syncNow: 'Đồng bộ ngay',
    connected: 'Đã kết nối', disconnected: 'Chưa kết nối',
  },
  id: {
    dashboard: 'Dasbor', tasks: 'Tugas', weekly: 'Mingguan', today: 'Hari ini',
    emailSync: 'Sinkronisasi email', addTask: '+ Tambah tugas', profile: 'Profil',
    logout: 'Keluar', changePassword: 'Ubah kata sandi', welcome: 'Selamat datang',
    yourTasks: 'Tugas Anda', noTasks: 'Belum ada tugas', addNewTask: 'Tambah tugas baru',
    editTask: 'Edit tugas', title: 'Judul', description: 'Deskripsi',
    dueDate: 'Tanggal jatuh tempo', priority: 'Prioritas', course: 'Kursus',
    low: 'Rendah', medium: 'Sedang', high: 'Tinggi', save: 'Simpan', cancel: 'Batal',
    delete: 'Hapus', complete: 'Selesai', settings: 'Pengaturan',
    language: 'Bahasa', aiAssistant: 'Asisten belajar AI',
    connectMicrosoft: 'Masuk dengan Microsoft', syncNow: 'Sinkronkan sekarang',
    connected: 'Terhubung', disconnected: 'Tidak terhubung',
  },
  ms: {
    dashboard: 'Papan pemuka', tasks: 'Tugas', weekly: 'Mingguan', today: 'Hari ini',
    emailSync: 'Selaras e-mel', addTask: '+ Tambah tugas', profile: 'Profil',
    logout: 'Log keluar', changePassword: 'Tukar kata laluan', welcome: 'Selamat datang',
    yourTasks: 'Tugas anda', noTasks: 'Belum ada tugas', addNewTask: 'Tambah tugas baharu',
    editTask: 'Edit tugas', title: 'Tajuk', description: 'Perihal',
    dueDate: 'Tarikh akhir', priority: 'Keutamaan', course: 'Kursus',
    low: 'Rendah', medium: 'Sederhana', high: 'Tinggi', save: 'Simpan', cancel: 'Batal',
    delete: 'Padam', complete: 'Selesai', settings: 'Tetapan',
    language: 'Bahasa', aiAssistant: 'Pembantu AI Pembelajaran',
    connectMicrosoft: 'Log masuk dengan Microsoft', syncNow: 'Selaras sekarang',
    connected: 'Disambung', disconnected: 'Tidak disambung',
  },
  uk: {
    dashboard: 'Панель', tasks: 'Завдання', weekly: 'Тижневий', today: 'Сьогодні',
    emailSync: 'Синхронізація пошти', addTask: '+ Додати завдання', profile: 'Профіль',
    logout: 'Вийти', changePassword: 'Змінити пароль', welcome: 'Ласкаво просимо',
    yourTasks: 'Ваші завдання', noTasks: 'Завдань ще немає', addNewTask: 'Додати нове завдання',
    editTask: 'Редагувати завдання', title: 'Назва', description: 'Опис',
    dueDate: 'Термін', priority: 'Пріоритет', course: 'Курс',
    low: 'Низький', medium: 'Середній', high: 'Високий', save: 'Зберегти', cancel: 'Скасувати',
    delete: 'Видалити', complete: 'Завершити', settings: 'Налаштування',
    language: 'Мова', aiAssistant: 'AI Помічник навчання',
    connectMicrosoft: 'Увійти через Microsoft', syncNow: 'Синхронізувати',
    connected: 'Підключено', disconnected: 'Відключено',
  },
  cs: {
    dashboard: 'Nástěnka', tasks: 'Úkoly', weekly: 'Týdenní', today: 'Dnes',
    emailSync: 'Synchronizace e-mailu', addTask: '+ Přidat úkol', profile: 'Profil',
    logout: 'Odhlásit se', changePassword: 'Změnit heslo', welcome: 'Vítejte',
    yourTasks: 'Vaše úkoly', noTasks: 'Zatím žádné úkoly', addNewTask: 'Přidat nový úkol',
    editTask: 'Upravit úkol', title: 'Název', description: 'Popis',
    dueDate: 'Termín', priority: 'Priorita', course: 'Kurz',
    low: 'Nízká', medium: 'Střední', high: 'Vysoká', save: 'Uložit', cancel: 'Zrušit',
    delete: 'Smazat', complete: 'Dokončit', settings: 'Nastavení',
    language: 'Jazyk', aiAssistant: 'AI Studijní asistent',
    connectMicrosoft: 'Přihlásit přes Microsoft', syncNow: 'Synchronizovat',
    connected: 'Připojeno', disconnected: 'Odpojeno',
  },
  el: {
    dashboard: 'Πίνακας ελέγχου', tasks: 'Εργασίες', weekly: 'Εβδομαδιαίο', today: 'Σήμερα',
    emailSync: 'Συγχρονισμός email', addTask: '+ Προσθήκη εργασίας', profile: 'Προφίλ',
    logout: 'Αποσύνδεση', changePassword: 'Αλλαγή κωδικού', welcome: 'Καλώς ήρθες',
    yourTasks: 'Οι εργασίες σου', noTasks: 'Δεν υπάρχουν εργασίες', addNewTask: 'Προσθήκη νέας εργασίας',
    editTask: 'Επεξεργασία εργασίας', title: 'Τίτλος', description: 'Περιγραφή',
    dueDate: 'Ημερομηνία λήξης', priority: 'Προτεραιότητα', course: 'Μάθημα',
    low: 'Χαμηλή', medium: 'Μέτρια', high: 'Υψηλή', save: 'Αποθήκευση', cancel: 'Ακύρωση',
    delete: 'Διαγραφή', complete: 'Ολοκλήρωση', settings: 'Ρυθμίσεις',
    language: 'Γλώσσα', aiAssistant: 'Βοηθός AI μάθησης',
    connectMicrosoft: 'Σύνδεση με Microsoft', syncNow: 'Συγχρονισμός τώρα',
    connected: 'Συνδεδεμένο', disconnected: 'Αποσυνδεδεμένο',
  },
  he: {
    dashboard: 'לוח בקרה', tasks: 'משימות', weekly: 'שבועי', today: 'היום',
    emailSync: 'סנכרון דואר', addTask: '+ הוסף משימה', profile: 'פרופיל',
    logout: 'התנתק', changePassword: 'שנה סיסמה', welcome: 'ברוך הבא',
    yourTasks: 'המשימות שלך', noTasks: 'אין משימות עדיין', addNewTask: 'הוסף משימה חדשה',
    editTask: 'ערוך משימה', title: 'כותרת', description: 'תיאור',
    dueDate: 'תאריך יעד', priority: 'עדיפות', course: 'קורס',
    low: 'נמוכה', medium: 'בינונית', high: 'גבוהה', save: 'שמור', cancel: 'בטל',
    delete: 'מחק', complete: 'השלם', settings: 'הגדרות',
    language: 'שפה', aiAssistant: 'עוזר AI ללימודים',
    connectMicrosoft: 'התחבר עם Microsoft', syncNow: 'סנכרן עכשיו',
    connected: 'מחובר', disconnected: 'מנותק',
  },
  hu: {
    dashboard: 'Irányítópult', tasks: 'Feladatok', weekly: 'Heti', today: 'Ma',
    emailSync: 'E-mail szinkronizálás', addTask: '+ Feladat hozzáadása', profile: 'Profil',
    logout: 'Kijelentkezés', changePassword: 'Jelszó módosítása', welcome: 'Üdvözöljük',
    yourTasks: 'A feladataid', noTasks: 'Még nincs feladat', addNewTask: 'Új feladat hozzáadása',
    editTask: 'Feladat szerkesztése', title: 'Cím', description: 'Leírás',
    dueDate: 'Határidő', priority: 'Prioritás', course: 'Kurzus',
    low: 'Alacsony', medium: 'Közepes', high: 'Magas', save: 'Mentés', cancel: 'Mégse',
    delete: 'Törlés', complete: 'Befejezés', settings: 'Beállítások',
    language: 'Nyelv', aiAssistant: 'AI Tanulási Asszisztens',
    connectMicrosoft: 'Bejelentkezés Microsoft-fiókkal', syncNow: 'Szinkronizálás most',
    connected: 'Csatlakoztatva', disconnected: 'Leválasztva',
  },
  ro: {
    dashboard: 'Panou', tasks: 'Activități', weekly: 'Săptămânal', today: 'Astăzi',
    emailSync: 'Sincronizare e-mail', addTask: '+ Adaugă activitate', profile: 'Profil',
    logout: 'Deconectare', changePassword: 'Schimbă parola', welcome: 'Bine ai venit',
    yourTasks: 'Activitățile tale', noTasks: 'Încă nu există activități', addNewTask: 'Adaugă activitate nouă',
    editTask: 'Editează activitatea', title: 'Titlu', description: 'Descriere',
    dueDate: 'Termen limită', priority: 'Prioritate', course: 'Curs',
    low: 'Scăzută', medium: 'Medie', high: 'Ridicată', save: 'Salvează', cancel: 'Anulează',
    delete: 'Șterge', complete: 'Finalizează', settings: 'Setări',
    language: 'Limbă', aiAssistant: 'Asistent AI de studiu',
    connectMicrosoft: 'Conectează-te cu Microsoft', syncNow: 'Sincronizează acum',
    connected: 'Conectat', disconnected: 'Deconectat',
  },
  sk: {
    dashboard: 'Nástenka', tasks: 'Úlohy', weekly: 'Týždenný', today: 'Dnes',
    emailSync: 'Synchronizácia e-mailu', addTask: '+ Pridať úlohu', profile: 'Profil',
    logout: 'Odhlásiť sa', changePassword: 'Zmeniť heslo', welcome: 'Vitajte',
    yourTasks: 'Vaše úlohy', noTasks: 'Zatiaľ žiadne úlohy', addNewTask: 'Pridať novú úlohu',
    editTask: 'Upraviť úlohu', title: 'Názov', description: 'Popis',
    dueDate: 'Termín', priority: 'Priorita', course: 'Kurz',
    low: 'Nízka', medium: 'Stredná', high: 'Vysoká', save: 'Uložiť', cancel: 'Zrušiť',
    delete: 'Vymazať', complete: 'Dokončiť', settings: 'Nastavenia',
    language: 'Jazyk', aiAssistant: 'AI Študijný asistent',
    connectMicrosoft: 'Prihlásiť sa cez Microsoft', syncNow: 'Synchronizovať',
    connected: 'Pripojené', disconnected: 'Odpojené',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড', tasks: 'কাজ', weekly: 'সাপ্তাহিক', today: 'আজ',
    emailSync: 'ইমেইল সিঙ্ক', addTask: '+ কাজ যোগ করুন', profile: 'প্রোফাইল',
    logout: 'লগ আউট', changePassword: 'পাসওয়ার্ড পরিবর্তন', welcome: 'স্বাগতম',
    yourTasks: 'আপনার কাজ', noTasks: 'এখনও কোন কাজ নেই', addNewTask: 'নতুন কাজ যোগ করুন',
    editTask: 'কাজ সম্পাদনা', title: 'শিরোনাম', description: 'বিবরণ',
    dueDate: 'নির্ধারিত তারিখ', priority: 'অগ্রাধিকার', course: 'কোর্স',
    low: 'কম', medium: 'মাঝারি', high: 'উচ্চ', save: 'সংরক্ষণ', cancel: 'বাতিল',
    delete: 'মুছুন', complete: 'সম্পন্ন', settings: 'সেটিংস',
    language: 'ভাষা', aiAssistant: 'AI অধ্যয়ন সহায়ক',
    connectMicrosoft: 'Microsoft দিয়ে লগ ইন', syncNow: 'এখন সিঙ্ক করুন',
    connected: 'সংযুক্ত', disconnected: 'সংযুক্ত নেই',
    taskAdded: 'কাজ যোগ হয়েছে!', taskUpdated: 'কাজ আপডেট হয়েছে!', taskDeleted: 'কাজ মুছে ফেলা হয়েছে!',
    deleteConfirm: 'আপনি কি এই কাজটি মুছতে চান?',
    notifications: 'বিজ্ঞপ্তি', noNotifications: 'কোন বিজ্ঞপ্তি নেই',
    markAllRead: 'সব পড়া হয়েছে', overdue: 'বিলম্বিত', dueToday: 'আজের মধ্যে', dueTomorrow: 'আগামীকাল',
    completed: 'সম্পন্ন', pending: 'বিচারাধীন', all: 'সব', search: 'অনুসন্ধান',
    addFirstTask: 'আপনার প্রথম কাজ যোগ করুন!', focusMode: 'ফোকাস মোড', startFocus: 'ফোকাস শুরু',
    pause: 'বিরতি', resume: 'চালিয়ে যান', reset: 'পুনরায় সেট', ready: 'প্রস্তুত', focusing: 'ফোকাস', paused: 'বিরত',
    sessionsToday: 'আজকের সেশন', generatingPlan: 'আপনার পরিকল্পনা তৈরি...', noPendingTasks: 'কোন কাজ নেই!',
    addTasksFromDashboard: 'ড্যাশবোর্ড থেকে কাজ যোগ করুন', loadingCalendar: 'ক্যালেন্ডার লোড হচ্ছে...',
    refresh: 'রিফ্রেশ', tasksPending: 'বিচারাধীন কাজ', completedToday: 'আজ সম্পন্ন',
    recommendedTaskOrder: 'প্রস্তাবিত ক্রম', noTasks: 'কোন কাজ নেই', askMeAnything: 'আমাকে যা খুশি জিজ্ঞেস করুন...',
    send: 'পাঠান', noLanguagesFound: 'কোন ভাষা পাওয়া যায়নি', enterYourEmail: 'আপনার ইমেইল',
    enterPassword: 'পাসওয়ার্ড', defaultDuration: '60',
  },
  'zh-TW': {
    dashboard: '儀表板', tasks: '任務', weekly: '每週', today: '今天',
    emailSync: '郵件同步', addTask: '+ 添加任務', profile: '個人資料',
    logout: '登出', changePassword: '更改密碼', welcome: '歡迎',
    yourTasks: '您的任務', noTasks: '暫無任務', addNewTask: '添加新任務',
    editTask: '編輯任務', title: '標題', description: '描述',
    dueDate: '截止日期', priority: '優先級', course: '課程',
    low: '低', medium: '中', high: '高', save: '儲存', cancel: '取消',
    delete: '刪除', complete: '完成', settings: '設定',
    language: '語言', aiAssistant: 'AI學習助手',
    connectMicrosoft: '使用Microsoft登入', syncNow: '立即同步',
    connected: '已連接', disconnected: '未連接',
    taskAdded: '任務已添加！', taskUpdated: '任務已更新！', taskDeleted: '任務已刪除！',
    deleteConfirm: '確定要刪除此任務嗎？',
    notifications: '通知', noNotifications: '暫無通知',
    markAllRead: '全部標記為已讀', overdue: '已逾期', dueToday: '今天到期', dueTomorrow: '明天到期',
    completed: '已完成', pending: '待處理', all: '全部', search: '搜索',
    addFirstTask: '添加您的第一個任務！', focusMode: '專注模式', startFocus: '開始專注',
    pause: '暫停', resume: '繼續', reset: '重置', ready: '就緒', focusing: '專注中', paused: '已暫停',
    sessionsToday: '今日專注次數', generatingPlan: '正在生成您的計劃...', noPendingTasks: '沒有待處理任務！',
    addTasksFromDashboard: '從儀表板添加任務', loadingCalendar: '正在加載日曆...',
    refresh: '刷新', tasksPending: '待處理任務', completedToday: '今日已完成',
    recommendedTaskOrder: '推薦順序', noTasks: '暫無任務', askMeAnything: '問我任何問題...',
    send: '發送', noLanguagesFound: '未找到語言', enterYourEmail: '您的郵箱',
    enterPassword: '密碼', defaultDuration: '60',
  },
  ja: {
    dashboard: 'ダッシュボード', tasks: 'タスク', weekly: '毎週', today: '今日',
    emailSync: 'メール同期', addTask: '+ タスク追加', profile: 'プロフィール',
    logout: 'ログアウト', changePassword: 'パスワード変更', welcome: 'ようこそ',
    yourTasks: 'あなたのタスク', noTasks: 'タスクなし', addNewTask: '新しいタスク追加',
    editTask: 'タスク編集', title: 'タイトル', description: '説明',
    dueDate: '期限', priority: '優先度', course: 'コース',
    low: '低', medium: '中', high: '高', save: '保存', cancel: 'キャンセル',
    delete: '削除', complete: '完了', settings: '設定',
    language: '言語', aiAssistant: 'AI学習アシスタント',
    connectMicrosoft: 'Microsoftでログイン', syncNow: '今すぐ同期',
    connected: '接続済み', disconnected: '未接続',
    taskAdded: 'タスク追加！', taskUpdated: 'タスク更新！', taskDeleted: 'タスク削除！',
    deleteConfirm: 'このタスクを削除しますか？',
    notifications: '通知', noNotifications: '通知なし',
    markAllRead: 'すべて既読', overdue: '期限超過', dueToday: '今日', dueTomorrow: '明日',
    completed: '完了', pending: '保留', all: 'すべて', search: '検索',
    addFirstTask: '最初のタスクを追加！', focusMode: 'フォーカスモード', startFocus: 'フォーカス開始',
    pause: '一時停止', resume: '再開', reset: 'リセット', ready: '準備完了', focusing: '集中中', paused: '停止中',
    sessionsToday: '今日のセッション', generatingPlan: '計画作成中...', noPendingTasks: '保留タスクなし！',
    addTasksFromDashboard: 'ダッシュボードから追加', loadingCalendar: '読み込み中...',
    refresh: '更新', tasksPending: '保留タスク', completedToday: '今日完了',
    recommendedTaskOrder: '推奨順序', noTasks: 'タスクなし', askMeAnything: '何をでも聞いて！',
    send: '送信', noLanguagesFound: '言語見つからず', enterYourEmail: 'メール',
    enterPassword: 'パスワード', defaultDuration: '60',
  },
  ko: {
    dashboard: '대시보드', tasks: '작업', weekly: '주간', today: '오늘',
    emailSync: '이메일 동기화', addTask: '+ 작업 추가', profile: '프로필',
    logout: '로그아웃', changePassword: '비밀번호 변경', welcome: '환영합니다',
    yourTasks: '내 작업', noTasks: '작업 없음', addNewTask: '새 작업 추가',
    editTask: '작업 편집', title: '제목', description: '설명',
    dueDate: '마감일', priority: '우선순위', course: '강좌',
    low: '낮음', medium: '중간', high: '높음', save: '저장', cancel: '취소',
    delete: '삭제', complete: '완료', settings: '설정',
    language: '언어', aiAssistant: 'AI 학습 도우미',
    connectMicrosoft: 'Microsoft로 로그인', syncNow: '지금 동기화',
    connected: '연결됨', disconnected: '연결 안됨',
    taskAdded: '작업 추가됨！', taskUpdated: '작업 업데이트됨！', taskDeleted: '작업 삭제됨！',
    deleteConfirm: '이 작업을 삭제하시겠습니까？',
    notifications: '알림', noNotifications: '알림 없음',
    markAllRead: '모두 읽음으로 표시', overdue: '기한 초과', dueToday: '오늘', dueTomorrow: '내일',
    completed: '완료', pending: '대기중', all: '전체', search: '검색',
    addFirstTask: '첫 번째 작업 추가！', focusMode: '집중 모드', startFocus: '집중 시작',
    pause: '일시정지', resume: '재개', reset: '초기화', ready: '준비', focusing: '집중중', paused: '일시정지됨',
    sessionsToday: '오늘 세션', generatingPlan: '계획 생성중...', noPendingTasks: '대기 작업 없음！',
    addTasksFromDashboard: '대시보드에서 추가', loadingCalendar: '달력 로딩중...',
    refresh: '새로고침', tasksPending: '대기 작업', completedToday: '오늘 완료',
    recommendedTaskOrder: '권장 순서', noTasks: '작업 없음', askMeAnything: '무엇이든 물어보세요...',
    send: '보내기', noLanguagesFound: '언어 찾을 수 없음', enterYourEmail: '이메일',
    enterPassword: '비밀번호', defaultDuration: '60',
  },
  it: {
    dashboard: 'Dashboard', tasks: 'Attività', weekly: 'Settimanale', today: 'Oggi',
    emailSync: 'Sync Email', addTask: '+ Aggiungi', profile: 'Profilo',
    logout: 'Disconnetti', changePassword: 'Cambia Password', welcome: 'Benvenuto',
    yourTasks: 'Le tue attività', noTasks: 'Nessuna attività', addNewTask: 'Aggiungi nuova',
    editTask: 'Modifica', title: 'Titolo', description: 'Descrizione',
    dueDate: 'Scadenza', priority: 'Priorità', course: 'Corso',
    low: 'Bassa', media: 'Media', high: 'Alta', save: 'Salva', cancel: 'Annulla',
    delete: 'Elimina', complete: 'Completa', settings: 'Impostazioni',
    language: 'Lingua', aiAssistant: 'Assistente AI',
    connectMicrosoft: 'Accedi con Microsoft', syncNow: 'Sincronizza',
    connected: 'Connesso', disconnected: 'Disconnesso',
    taskAdded: 'Attività aggiunta！', taskUpdated: 'Attività aggiornata！', taskDeleted: 'Attività eliminata！',
    deleteConfirm: 'Eliminare questa attività？',
    notifications: 'Notifiche', noNotifications: 'Nessuna notifica',
    markAllRead: 'Segna tutto come letto', overdue: 'In ritardo', dueToday: 'Oggi', dueTomorrow: 'Domani',
    completed: 'Completato', pending: 'In sospeso', all: 'Tutti', search: 'Cerca',
    addFirstTask: 'Aggiungi la prima attività！', focusMode: 'Modalità Focus', startFocus: 'Inizia Focus',
    pause: 'Pausa', resume: 'Riprendi', reset: 'Resetta', ready: 'Pronto', focusing: 'In focus', paused: 'In pausa',
    sessionsToday: 'Sessioni oggi', generatingPlan: 'Genero piano...', noPendingTasks: 'Niente in sospeso！',
    addTasksFromDashboard: 'Aggiungi da dashboard', loadingCalendar: 'Carico calendario...',
    refresh: 'Aggiorna', tasksPending: 'In sospeso', completedToday: 'Completato oggi',
    recommendedTaskOrder: 'Ordine consigliato', noTasks: 'Nessuna attività', askMeAnything: 'Chiedimi...',
    send: 'Invia', noLanguagesFound: 'Nessuna lingua', enterYourEmail: 'Tua email',
    enterPassword: 'Password', defaultDuration: '60',
  },
  pt: {
    dashboard: 'Painel', tasks: 'Tarefas', weekly: 'Semanal', today: 'Hoje',
    emailSync: 'Sincronizar Email', addTask: '+ Adicionar', profile: 'Perfil',
    logout: 'Sair', changePassword: 'Alterar Senha', welcome: 'Bem-vindo',
    yourTasks: 'Suas tarefas', noTasks: 'Sem tarefas', addNewTask: 'Nova tarefa',
    editTask: 'Editar', title: 'Título', description: 'Descrição',
    dueDate: 'Data limite', priority: 'Prioridade', course: 'Curso',
    low: 'Baixa', medium: 'Média', high: 'Alta', save: 'Salvar', cancel: 'Cancelar',
    delete: 'Excluir', complete: 'Completar', settings: 'Configurações',
    language: 'Idioma', aiAssistant: 'Assistente AI',
    connectMicrosoft: 'Entrar com Microsoft', syncNow: 'Sincronizar',
    connected: 'Conectado', disconnected: 'Desconectado',
    taskAdded: 'Tarefa adicionada！', taskUpdated: 'Tarefa atualizada！', taskDeleted: 'Tarefa excluida！',
    deleteConfirm: 'Excluir esta tarefa？',
    notifications: 'Notificações', noNotifications: 'Sem notificações',
    markAllRead: 'Marcar tudo como lido', overdue: 'Atrasado', dueToday: 'Hoje', dueTomorrow: 'Amanhã',
    completed: 'Completo', pending: 'Pendente', all: 'Todos', search: 'Buscar',
    addFirstTask: 'Adicione sua primeira tarefa！', focusMode: 'Modo Foco', startFocus: 'Iniciar Foco',
    pause: 'Pausar', resume: 'Retomar', reset: 'Reiniciar', ready: 'Pronto', focusing: 'Focado', paused: 'Pausado',
    sessionsToday: 'Sessões hoje', generatingPlan: 'Gerando plano...', noPendingTasks: 'Sem tarefas pendentes！',
    addTasksFromDashboard: 'Adicionar do painel', loadingCalendar: 'Carregando calendário...',
    refresh: 'Atualizar', tasksPending: 'Pendentes', completedToday: 'Completo hoje',
    recommendedTaskOrder: 'Ordem recomendada', noTasks: 'Sem tarefas', askMeAnything: 'Pergunte qualquer coisa...',
    send: 'Enviar', noLanguagesFound: 'Nenhuma língua', enterYourEmail: 'Seu email',
    enterPassword: 'Senha', defaultDuration: '60',
  },
  ru: {
    dashboard: 'Панель', tasks: 'Задачи', weekly: 'Неделя', today: 'Сегодня',
    emailSync: 'Синхр. почты', addTask: '+ Добавить', profile: 'Профиль',
    logout: 'Выйти', changePassword: 'Изменить пароль', welcome: 'Добро пожаловать',
    yourTasks: 'Ваши задачи', noTasks: 'Нет задач', addNewTask: 'Новая задача',
    editTask: 'Редактировать', title: 'Название', description: 'Описание',
    dueDate: 'Срок', priority: 'Приоритет', course: 'Курс',
    low: 'Низкий', medium: 'Средний', high: 'Высокий', save: 'Сохранить', cancel: 'Отмена',
    delete: 'Удалить', complete: 'Завершить', settings: 'Настройки',
    language: 'Язык', aiAssistant: 'AI помощник',
    connectMicrosoft: 'Войти через Microsoft', syncNow: 'Синхронизировать',
    connected: 'Подключено', disconnected: 'Отключено',
    taskAdded: 'Задача добавлена！', taskUpdated: 'Задача обновлена！', taskDeleted: 'Задача удалена！',
    deleteConfirm: 'Удалить эту задачу？',
    notifications: 'Уведомления', noNotifications: 'Нет уведомлений',
    markAllRead: 'Отметить все прочитанными', overdue: 'Просрочено', dueToday: 'Сегодня', dueTomorrow: 'Завтра',
    completed: 'Завершено', pending: 'Ожидает', all: 'Все', search: 'Поиск',
    addFirstTask: 'Добавьте первую задачу！', focusMode: 'Режим фокуса', startFocus: 'Начать фокус',
    pause: 'Пауза', resume: 'Продолжить', reset: 'Сброс', ready: 'Готов', focusing: 'Фокус', paused: 'Приостановлено',
    sessionsToday: 'Сессий сегодня', generatingPlan: 'Создание плана...', noPendingTasks: 'Нет задач！',
    addTasksFromDashboard: 'Добавить с панели', loadingCalendar: 'Загрузка календаря...',
    refresh: 'Обновить', tasksPending: 'Ожидают', completedToday: 'Завершено сегодня',
    recommendedTaskOrder: 'Рекомендуемый порядок', noTasks: 'Нет задач', askMeAnything: 'Спросите меня...',
    send: 'Отправить', noLanguagesFound: 'Языки не найдены', enterYourEmail: 'Ваш email',
    enterPassword: 'Пароль', defaultDuration: '60',
  },
  tr: {
    dashboard: 'Pano', tasks: 'Görevler', weekly: 'Haftalık', today: 'Bugün',
    emailSync: 'E-posta Senk.', addTask: '+ Ekle', profile: 'Profil',
    logout: 'Çıkış', changePassword: 'Şifre değiştir', welcome: 'Hoş geldin',
    yourTasks: 'Görevlerin', noTasks: 'Görev yok', addNewTask: 'Yeni görev ekle',
    editTask: 'Düzenle', title: 'Başlık', description: 'Açıklama',
    dueDate: 'Bitiş tarihi', priority: 'Öncelik', course: 'Ders',
    low: 'Düşük', medium: 'Orta', high: 'Yüksek', save: 'Kaydet', cancel: 'İptal',
    delete: 'Sil', complete: 'Tamamla', settings: 'Ayarlar',
    language: 'Dil', aiAssistant: 'AI Asistanı',
    connectMicrosoft: 'Microsoft ile giriş', syncNow: 'Senkronize et',
    connected: 'Bağlı', disconnected: 'Bağlı değil',
    taskAdded: 'Görev eklendi！', taskUpdated: 'Görev güncellendi！', taskDeleted: 'Görev silindi！',
    deleteConfirm: 'Bu görevi sil？',
    notifications: 'Bildirimler', noNotifications: 'Bildirim yok',
    markAllRead: 'Tümünü okundu say', overdue: 'Gecikmiş', dueToday: 'Bugün', dueTomorrow: 'Yarın',
    completed: 'Tamamlandı', pending: 'Bekliyor', all: 'Tümü', search: 'Ara',
    addFirstTask: 'İlk görevini ekle！', focusMode: 'Odak Modu', startFocus: 'Odaklan',
    pause: 'Duraklat', resume: 'Devam et', reset: 'Sıfırla', ready: 'Hazır', focusing: 'Odaklanıyor', paused: 'Duraklatıldı',
    sessionsToday: 'Bugünkü oturumlar', generatingPlan: 'Plan oluşturuluyor...', noPendingTasks: 'Bekleyen görev yok！',
    addTasksFromDashboard: 'Panodan ekle', loadingCalendar: 'Takvim yükleniyor...',
    refresh: 'Yenile', tasksPending: 'Bekleyen', completedToday: 'Bugün tamamlandı',
    recommendedTaskOrder: 'Önerilen sıra', noTasks: 'Görev yok', askMeAnything: 'Soru sor...',
    send: 'Gönder', noLanguagesFound: 'Dil bulunamadı', enterYourEmail: 'E-posta',
    enterPassword: 'Şifre', defaultDuration: '60',
  },
  nl: {
    dashboard: 'Dashboard', tasks: 'Taken', weekly: 'Wekelijks', today: 'Vandaag',
    emailSync: 'E-mail sync', addTask: '+ Toevoegen', profile: 'Profiel',
    logout: 'Uitloggen', changePassword: 'Wachtwoord wijzigen', welcome: 'Welkom',
    yourTasks: 'Jouw taken', noTasks: 'Geen taken', addNewTask: 'Nieuwe taak',
    editTask: 'Bewerken', title: 'Titel', description: 'Beschrijving',
    dueDate: 'Vervaldatum', priority: 'Prioriteit', course: 'Cursus',
    low: 'Laag', medium: 'Middel', high: 'Hoog', save: 'Opslaan', cancel: 'Annuleren',
    delete: 'Verwijderen', complete: 'Voltooien', settings: 'Instellingen',
    language: 'Taal', aiAssistant: 'AI Assistent',
    connectMicrosoft: 'Inloggen met Microsoft', syncNow: 'Nu synchroniseren',
    connected: 'Verbonden', disconnected: 'Niet verbonden',
    taskAdded: 'Taak toegevoegd！', taskUpdated: 'Taak bijgewerkt！', taskDeleted: 'Taak verwijderd！',
    deleteConfirm: 'Deze taak verwijderen？',
    notifications: 'Meldingen', noNotifications: 'Geen meldingen',
    markAllRead: 'Alles als gelezen', overdue: 'Te laat', dueToday: 'Vandaag', dueTomorrow: 'Morgen',
    completed: 'Voltooid', pending: 'In behandeling', all: 'Alle', search: 'Zoeken',
    addFirstTask: 'Voeg je eerste taak toe！', focusMode: 'Focus Modus', startFocus: 'Start Focus',
    pause: 'Pauze', resume: 'Hervat', reset: 'Reset', ready: 'Klaar', focusing: 'Focussen', paused: 'Gepauzeerd',
    sessionsToday: 'Sessies vandaag', generatingPlan: 'Plan genereren...', noPendingTasks: 'Geen openstaande taken！',
    addTasksFromDashboard: 'Toevoegen van dashboard', loadingCalendar: 'Kalender laden...',
    refresh: 'Vernieuwen', tasksPending: 'In behandeling', completedToday: 'Vandaag voltooid',
    recommendedTaskOrder: 'Aanbevolen volgorde', noTasks: 'Geen taken', askMeAnything: 'Vraag me alles...',
    send: 'Verzenden', noLanguagesFound: 'Geen talen', enterYourEmail: 'Je e-mail',
    enterPassword: 'Wachtwoord', defaultDuration: '60',
  },
  pl: {
    dashboard: 'Pulpit', tasks: 'Zadania', weekly: 'Tygodniowy', today: 'Dziś',
    emailSync: 'Sync Email', addTask: '+ Dodaj', profile: 'Profil',
    logout: 'Wyloguj', changePassword: 'Zmień hasło', welcome: 'Witaj',
    yourTasks: 'Twoje zadania', noTasks: 'Brak zadań', addNewTask: 'Nowe zadanie',
    editTask: 'Edytuj', title: 'Tytuł', description: 'Opis',
    dueDate: 'Termin', priority: 'Priorytet', course: 'Kurs',
    low: 'Niski', medium: 'Średni', high: 'Wysoki', save: 'Zapisz', cancel: 'Anuluj',
    delete: 'Usuń', complete: 'Ukończ', settings: 'Ustawienia',
    language: 'Język', aiAssistant: 'Asystent AI',
    connectMicrosoft: 'Zaloguj przez Microsoft', syncNow: 'Synchronizuj',
    connected: 'Połączony', disconnected: 'Rozłączony',
    taskAdded: 'Zadanie dodane！', taskUpdated: 'Zadanie zaktualizowane！', taskDeleted: 'Zadanie usunięte！',
    deleteConfirm: 'Usunąć to zadanie？',
    notifications: 'Powiadomienia', noNotifications: 'Brak powiadomień',
    markAllRead: 'Oznacz wszystko jako przeczytane', overdue: 'Zaległe', dueToday: 'Dziś', dueTomorrow: 'Jutro',
    completed: 'Ukończone', pending: 'Oczekujące', all: 'Wszystkie', search: 'Szukaj',
    addFirstTask: 'Dodaj pierwsze zadanie！', focusMode: 'Tryb Focus', startFocus: 'Rozpocznij Focus',
    pause: 'Pauza', resume: 'Wznów', reset: 'Resetuj', ready: 'Gotowy', focusing: 'Fokus', paused: 'Zatrzymany',
    sessionsToday: 'Sesji dzisiaj', generatingPlan: 'Generowanie planu...', noPendingTasks: 'Brak zadań！',
    addTasksFromDashboard: 'Dodaj z pulpitu', loadingCalendar: 'Ładowanie kalendarza...',
    refresh: 'Odśwież', tasksPending: 'Oczekujące', completedToday: 'Ukończone dziś',
    recommendedTaskOrder: 'Zalecana kolejność', noTasks: 'Brak zadań', askMeAnything: 'Pytaj mnie...',
    send: 'Wyślij', noLanguagesFound: 'Nie znaleziono języków', enterYourEmail: 'Twój email',
    enterPassword: 'Hasło', defaultDuration: '60',
  },
  uk: {
    dashboard: 'Панель', tasks: 'Завдання', weekly: 'Тижневий', today: 'Сьогодні',
    emailSync: 'Синхр. пошти', addTask: '+ Додати', profile: 'Профіль',
    logout: 'Вийти', changePassword: 'Змінити пароль', welcome: 'Ласкаво просимо',
    yourTasks: 'Ваші завдання', noTasks: 'Немає завдань', addNewTask: 'Нове завдання',
    editTask: 'Редагувати', title: 'Назва', description: 'Опис',
    dueDate: 'Термін', priority: 'Пріоритет', course: 'Курс',
    low: 'Низький', medium: 'Середній', high: 'Високий', save: 'Зберегти', cancel: 'Скасувати',
    delete: 'Видалити', complete: 'Завершити', settings: 'Налаштування',
    language: 'Мова', aiAssistant: 'AI Помічник',
    connectMicrosoft: 'Увійти через Microsoft', syncNow: 'Синхронізувати',
    connected: 'Підключено', disconnected: 'Відключено',
    taskAdded: 'Завдання додано！', taskUpdated: 'Завдання оновлено！', taskDeleted: 'Завдання видалено！',
    deleteConfirm: 'Видалити це завдання？',
    notifications: 'Сповіщення', noNotifications: 'Немає сповіщень',
    markAllRead: 'Позначити все прочитаним', overdue: 'Прострочено', dueToday: 'Сьогодні', dueTomorrow: 'Завтра',
    completed: 'Завершено', pending: 'Очікує', all: 'Всі', search: 'Пошук',
    addFirstTask: 'Додайте перше завдання！', focusMode: 'Режим фокусу', startFocus: 'Почати фокус',
    pause: 'Пауза', resume: 'Продовжити', reset: 'Скинути', ready: 'Готово', focusing: 'Фокус', paused: 'Призупинено',
    sessionsToday: 'Сесій сьогодні', generatingPlan: 'Створення плану...', noPendingTasks: 'Немає завдань！',
    addTasksFromDashboard: 'Додати з панелі', loadingCalendar: 'Завантаження календаря...',
    refresh: 'Оновити', tasksPending: 'Очікують', completedToday: 'Завершено сьогодні',
    recommendedTaskOrder: 'Рекомендований порядок', noTasks: 'Немає завдань', askMeAnything: 'Питайте мене...',
    send: 'Надіслати', noLanguagesFound: 'Мови не знайдено', enterYourEmail: 'Ваш email',
    enterPassword: 'Пароль', defaultDuration: '60',
  },
  th: {
    dashboard: 'แดชบอร์ด', tasks: 'งาน', weekly: 'รายสัปดาห์', today: 'วันนี้',
    emailSync: 'ซิงค์อีเมล', addTask: '+ เพิ่มงาน', profile: 'โปรไฟล์',
    logout: 'ออกจากระบบ', changePassword: 'เปลี่ยนรหัสผ่าน', welcome: 'ยินดีต้อนรับ',
    yourTasks: 'งานของคุณ', noTasks: 'ยังไม่มีงาน', addNewTask: 'เพิ่มงานใหม่',
    editTask: 'แก้ไขงาน', title: 'หัวข้อ', description: 'คำอธิบาย',
    dueDate: 'กำหนดส่ง', priority: 'ลำดับความสำคัญ', course: 'วิชา',
    low: 'ต่ำ', medium: 'ปานกลาง', high: 'สูง', save: 'บันทึก', cancel: 'ยกเลิก',
    delete: 'ลบ', complete: 'เสร็จสิ้น', settings: 'การตั้งค่า',
    language: 'ภาษา', aiAssistant: 'ผู้ช่วย AI',
    connectMicrosoft: 'เข้าสู่ระบบด้วย Microsoft', syncNow: 'ซิงค์ตอนนี้',
    connected: 'เชื่อมต่อแล้ว', disconnected: 'ไม่ได้เชื่อมต่อ',
    taskAdded: 'เพิ่มงานแล้ว！', taskUpdated: 'อัปเดตงานแล้ว！', taskDeleted: 'ลบงานแล้ว！',
    deleteConfirm: 'ต้องการลบงานนี้？',
    notifications: 'การแจ้งเตือน', noNotifications: 'ไม่มีการแจ้งเตือน',
    markAllRead: 'ทำเครื่องหมายทั้งหมด', overdue: 'เกินกำหนด', dueToday: 'วันนี้', dueTomorrow: 'พรุ่งนี้',
    completed: 'เสร็จสิ้น', pending: 'รอดำเนินการ', all: 'ทั้งหมด', search: 'ค้นหา',
    addFirstTask: 'เพิ่มงานแรกของคุณ！', focusMode: 'โหมดโฟกัส', startFocus: 'เริ่มโฟกัส',
    pause: 'หยุดชั่วคราว', resume: 'ดำเนินต่อ', reset: 'รีเซ็ต', ready: 'พร้อม', focusing: 'โฟกัส', paused: 'หยุดชั่วคราว',
    sessionsToday: 'เซสชันวันนี้', generatingPlan: 'กำลังสร้างแผน...', noPendingTasks: 'ไม่มีงานรอ！',
    addTasksFromDashboard: 'เพิ่มจากแดชบอร์ด', loadingCalendar: 'กำลังโหลดปฏิทิน...',
    refresh: 'รีเฟรช', tasksPending: 'งานรอ', completedToday: 'เสร็จวันนี้',
    recommendedTaskOrder: 'ลำดับที่แนะนำ', noTasks: 'ไม่มีงาน', askMeAnything: 'ถามได้เลย...',
    send: 'ส่ง', noLanguagesFound: 'ไม่พบภาษา', enterYourEmail: 'อีเมลของคุณ',
    enterPassword: 'รหัสผ่าน', defaultDuration: '60',
  },
  vi: {
    dashboard: 'Bảng điều khiển', tasks: 'Công việc', weekly: 'Hàng tuần', today: 'Hôm nay',
    emailSync: 'Đồng bộ Email', addTask: '+ Thêm', profile: 'Hồ sơ',
    logout: 'Đăng xuất', changePassword: 'Đổi mật khẩu', welcome: 'Chào mừng',
    yourTasks: 'Công việc của bạn', noTasks: 'Chưa có công việc', addNewTask: 'Thêm công việc mới',
    editTask: 'Sửa', title: 'Tiêu đề', description: 'Mô tả',
    dueDate: 'Ngày đến hạn', priority: 'Ưu tiên', course: 'Khóa học',
    low: 'Thấp', medium: 'Trung bình', high: 'Cao', save: 'Lưu', cancel: 'Hủy',
    delete: 'Xóa', complete: 'Hoàn thành', settings: 'Cài đặt',
    language: 'Ngôn ngữ', aiAssistant: 'Trợ lý AI',
    connectMicrosoft: 'Đăng nhập Microsoft', syncNow: 'Đồng bộ',
    connected: 'Đã kết nối', disconnected: 'Chưa kết nối',
    taskAdded: 'Đã thêm công việc！', taskUpdated: 'Đã cập nhật！', taskDeleted: 'Đã xóa！',
    deleteConfirm: 'Xóa công việc này？',
    notifications: 'Thông báo', noNotifications: 'Không có thông báo',
    markAllRead: 'Đánh dấu đã đọc', overdue: 'Quá hạn', dueToday: 'Hôm nay', dueTomorrow: 'Ngày mai',
    completed: 'Hoàn thành', pending: 'Chờ xử lý', all: 'Tất cả', search: 'Tìm kiếm',
    addFirstTask: 'Thêm công việc đầu tiên！', focusMode: 'Chế độ Focus', startFocus: 'Bắt đầu Focus',
    pause: 'Tạm dừng', resume: 'Tiếp tục', reset: 'Đặt lại', ready: 'Sẵn sàng', focusing: 'Đang focus', paused: 'Đã tạm dừng',
    sessionsToday: 'Phiên hôm nay', generatingPlan: 'Đang tạo kế hoạch...', noPendingTasks: 'Không có việc chờ！',
    addTasksFromDashboard: 'Thêm từ dashboard', loadingCalendar: 'Đang tải lịch...',
    refresh: 'Làm mới', tasksPending: 'Đang chờ', completedToday: 'Hoàn thành hôm nay',
    recommendedTaskOrder: 'Thứ tự đề xuất', noTasks: 'Không có việc', askMeAnything: 'Hỏi gì cũng được...',
    send: 'Gửi', noLanguagesFound: 'Không tìm thấy ngôn ngữ', enterYourEmail: 'Email của bạn',
    enterPassword: 'Mật khẩu', defaultDuration: '60',
  },
};

export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'es', name: 'Español', flag: '🇪🇸', dir: 'ltr' },
];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const [dir, setDir] = useState('ltr');

  useEffect(() => {
    const saved = localStorage.getItem('language');
    if (saved && translations[saved]) {
      setLanguage(saved);
    }
  }, []);

  useEffect(() => {
    const lang = languages.find(l => l.code === language);
    const newDir = lang?.dir || 'ltr';
    setDir(newDir);
    document.documentElement.dir = newDir;
    document.documentElement.lang = language;
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    if (language === 'en') {
      return translations.en[key] || key;
    }
    return translations.es[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
