import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard',
    tasks: 'Tasks',
    weekly: 'Weekly',
    today: 'Today',
    emailSync: 'Email Sync',
    addTask: '+ Add Task',
    profile: 'Profile',
    logout: 'Logout',
    changePassword: 'Change Password',
    welcome: 'Welcome',
    yourTasks: 'Your Tasks',
    noTasks: 'No tasks yet',
    addNewTask: 'Add New Task',
    editTask: 'Edit Task',
    title: 'Title',
    description: 'Description',
    dueDate: 'Due Date',
    priority: 'Priority',
    course: 'Course',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    complete: 'Complete',
    settings: 'Settings',
    language: 'Language',
    aiAssistant: 'AI Study Assistant',
    connectMicrosoft: 'Sign in with Microsoft',
    syncNow: 'Sync Now',
    connected: 'Connected',
    disconnected: 'Disconnected',
  },
  es: {
    dashboard: 'Panel',
    tasks: 'Tareas',
    weekly: 'Semanal',
    today: 'Hoy',
    emailSync: 'Sincronizar Email',
    addTask: '+ Agregar Tarea',
    profile: 'Perfil',
    logout: 'Cerrar Sesión',
    changePassword: 'Cambiar Contraseña',
    welcome: 'Bienvenido',
    yourTasks: 'Tus Tareas',
    noTasks: 'Sin tareas aún',
    addNewTask: 'Agregar Nueva Tarea',
    editTask: 'Editar Tarea',
    title: 'Título',
    description: 'Descripción',
    dueDate: 'Fecha de Vencimiento',
    priority: 'Prioridad',
    course: 'Curso',
    low: 'Baja',
    medium: 'Media',
    high: 'Alta',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    complete: 'Completar',
    settings: 'Configuración',
    language: 'Idioma',
    aiAssistant: 'Asistente de Estudio IA',
    connectMicrosoft: 'Iniciar sesión con Microsoft',
    syncNow: 'Sincronizar Ahora',
    connected: 'Conectado',
    disconnected: 'Desconectado',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    tasks: 'Tâches',
    weekly: 'Hebdomadaire',
    today: "Aujourd'hui",
    emailSync: 'Sync Email',
    addTask: '+ Ajouter Tâche',
    profile: 'Profil',
    logout: 'Déconnexion',
    changePassword: 'Changer le Mot de Passe',
    welcome: 'Bienvenue',
    yourTasks: 'Vos Tâches',
    noTasks: 'Pas encore de tâches',
    addNewTask: 'Ajouter Nouvelle Tâche',
    editTask: 'Modifier Tâche',
    title: 'Titre',
    description: 'Description',
    dueDate: "Date d'échéance",
    priority: 'Priorité',
    course: 'Cours',
    low: 'Basse',
    medium: 'Moyenne',
    high: 'Haute',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    complete: 'Terminer',
    settings: 'Paramètres',
    language: 'Langue',
    aiAssistant: 'Assistant Étude IA',
    connectMicrosoft: 'Se connecter avec Microsoft',
    syncNow: 'Synchroniser',
    connected: 'Connecté',
    disconnected: 'Déconnecté',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    tasks: 'المهام',
    weekly: 'أسبوعي',
    today: 'اليوم',
    emailSync: 'مزامنة البريد',
    addTask: '+ إضافة مهمة',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    changePassword: 'تغيير كلمة المرور',
    welcome: 'مرحبا',
    yourTasks: 'مهامك',
    noTasks: 'لا توجد مهام بعد',
    addNewTask: 'إضافة مهمة جديدة',
    editTask: 'تعديل المهمة',
    title: 'العنوان',
    description: 'الوصف',
    dueDate: 'تاريخ الاستحقاق',
    priority: 'الأولوية',
    course: 'المقرر',
    low: 'منخفضة',
    medium: 'متوسطة',
    high: 'عالية',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    complete: 'إكمال',
    settings: 'الإعدادات',
    language: 'اللغة',
    aiAssistant: 'مساعد الدراسة الذكي',
    connectMicrosoft: 'تسجيل الدخول عبر Microsoft',
    syncNow: 'مزامنة الآن',
    connected: 'متصل',
    disconnected: 'غير متصل',
  },
  de: {
    dashboard: 'Übersicht',
    tasks: 'Aufgaben',
    weekly: 'Woche',
    today: 'Heute',
    emailSync: 'E-Mail Sync',
    addTask: '+ Aufgabe hinzufügen',
    profile: 'Profil',
    logout: 'Abmelden',
    changePassword: 'Passwort ändern',
    welcome: 'Willkommen',
    yourTasks: 'Ihre Aufgaben',
    noTasks: 'Noch keine Aufgaben',
    addNewTask: 'Neue Aufgabe hinzufügen',
    editTask: 'Aufgabe bearbeiten',
    title: 'Titel',
    description: 'Beschreibung',
    dueDate: 'Fälligkeitsdatum',
    priority: 'Priorität',
    course: 'Kurs',
    low: 'Niedrig',
    medium: 'Mittel',
    high: 'Hoch',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    complete: 'Abschließen',
    settings: 'Einstellungen',
    language: 'Sprache',
    aiAssistant: 'KI Lernassistent',
    connectMicrosoft: 'Mit Microsoft anmelden',
    syncNow: 'Jetzt synchronisieren',
    connected: 'Verbunden',
    disconnected: 'Getrennt',
  },
  zh: {
    dashboard: '仪表板',
    tasks: '任务',
    weekly: '每周',
    today: '今天',
    emailSync: '邮件同步',
    addTask: '+ 添加任务',
    profile: '个人资料',
    logout: '退出登录',
    changePassword: '更改密码',
    welcome: '欢迎',
    yourTasks: '您的任务',
    noTasks: '暂无任务',
    addNewTask: '添加新任务',
    editTask: '编辑任务',
    title: '标题',
    description: '描述',
    dueDate: '截止日期',
    priority: '优先级',
    course: '课程',
    low: '低',
    medium: '中',
    high: '高',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    complete: '完成',
    settings: '设置',
    language: '语言',
    aiAssistant: 'AI学习助手',
    connectMicrosoft: '使用Microsoft登录',
    syncNow: '立即同步',
    connected: '已连接',
    disconnected: '未连接',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    tasks: 'कार्य',
    weekly: 'साप्ताहिक',
    today: 'आज',
    emailSync: 'ईमेल सिंक',
    addTask: '+ कार्य जोड़ें',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट',
    changePassword: 'पासवर्ड बदलें',
    welcome: 'स्वागत है',
    yourTasks: 'आपके कार्य',
    noTasks: 'अभी तक कोई कार्य नहीं',
    addNewTask: 'नया कार्य जोड़ें',
    editTask: 'कार्य संपादित करें',
    title: 'शीर्षक',
    description: 'विवरण',
    dueDate: 'नियत तारीख',
    priority: 'प्राथमिकता',
    course: 'कोर्स',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    complete: 'पूर्ण',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    aiAssistant: 'AI अध्ययन सहायक',
    connectMicrosoft: 'Microsoft से कनेक्ट करें',
    syncNow: 'अभी सिंक करें',
    connected: 'कनेक्टेड',
    disconnected: 'डिस्कनेक्टेड',
  },
  pt: {
    dashboard: 'Painel',
    tasks: 'Tarefas',
    weekly: 'Semanal',
    today: 'Hoje',
    emailSync: 'Sincronizar Email',
    addTask: '+ Adicionar Tarefa',
    profile: 'Perfil',
    logout: 'Sair',
    changePassword: 'Alterar Senha',
    welcome: 'Bem-vindo',
    yourTasks: 'Suas Tarefas',
    noTasks: 'Nenhuma tarefa ainda',
    addNewTask: 'Adicionar Nova Tarefa',
    editTask: 'Editar Tarefa',
    title: 'Título',
    description: 'Descrição',
    dueDate: 'Data de Vencimento',
    priority: 'Prioridade',
    course: 'Curso',
    low: 'Baixa',
    medium: 'Média',
    high: 'Alta',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    complete: 'Concluir',
    settings: 'Configurações',
    language: 'Idioma',
    aiAssistant: 'Assistente de Estudo IA',
    connectMicrosoft: 'Entrar com Microsoft',
    syncNow: 'Sincronizar Agora',
    connected: 'Conectado',
    disconnected: 'Desconectado',
  },
  ja: {
    dashboard: 'ダッシュボード',
    tasks: 'タスク',
    weekly: '毎週',
    today: '今日',
    emailSync: 'メール同期',
    addTask: '+ タスクを追加',
    profile: 'プロフィール',
    logout: 'ログアウト',
    changePassword: 'パスワードを変更',
    welcome: 'ようこそ',
    yourTasks: 'あなたのタスク',
    noTasks: 'タスクはまだありません',
    addNewTask: '新しいタスクを追加',
    editTask: 'タスクを編集',
    title: 'タイトル',
    description: '説明',
    dueDate: '期限',
    priority: '優先度',
    course: 'コース',
    low: '低',
    medium: '中',
    high: '高',
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    complete: '完了',
    settings: '設定',
    language: '言語',
    aiAssistant: 'AI学習アシスタント',
    connectMicrosoft: 'Microsoftでサインイン',
    syncNow: '今すぐ同期',
    connected: '接続済み',
    disconnected: '未接続',
  },
  ko: {
    dashboard: '대시보드',
    tasks: '작업',
    weekly: '주간',
    today: '오늘',
    emailSync: '이메일 동기화',
    addTask: '+ 작업 추가',
    profile: '프로필',
    logout: '로그아웃',
    changePassword: '비밀번호 변경',
    welcome: '환영합니다',
    yourTasks: '내 작업',
    noTasks: '아직 작업이 없습니다',
    addNewTask: '새 작업 추가',
    editTask: '작업 편집',
    title: '제목',
    description: '설명',
    dueDate: '마감일',
    priority: '우선순위',
    course: '강좌',
    low: '낮음',
    medium: '중간',
    high: '높음',
    save: '저장',
    cancel: '취소',
    delete: '삭제',
    complete: '완료',
    settings: '설정',
    language: '언어',
    aiAssistant: 'AI 학습 도우미',
    connectMicrosoft: 'Microsoft로 로그인',
    syncNow: '지금 동기화',
    connected: '연결됨',
    disconnected: '연결 안됨',
  },
  ru: {
    dashboard: 'Панель',
    tasks: 'Задачи',
    weekly: 'Неделя',
    today: 'Сегодня',
    emailSync: 'Синхронизация почты',
    addTask: '+ Добавить задачу',
    profile: 'Профиль',
    logout: 'Выйти',
    changePassword: 'Изменить пароль',
    welcome: 'Добро пожаловать',
    yourTasks: 'Ваши задачи',
    noTasks: 'Пока нет задач',
    addNewTask: 'Добавить новую задачу',
    editTask: 'Редактировать задачу',
    title: 'Название',
    description: 'Описание',
    dueDate: 'Срок',
    priority: 'Приоритет',
    course: 'Курс',
    low: 'Низкий',
    medium: 'Средний',
    high: 'Высокий',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    complete: 'Завершить',
    settings: 'Настройки',
    language: 'Язык',
    aiAssistant: 'AI Помощник по учебе',
    connectMicrosoft: 'Войти через Microsoft',
    syncNow: 'Синхронизировать',
    connected: 'Подключено',
    disconnected: 'Отключено',
  },
  it: {
    dashboard: 'Dashboard',
    tasks: 'Attività',
    weekly: 'Settimanale',
    today: 'Oggi',
    emailSync: 'Sincronizza Email',
    addTask: '+ Aggiungi Attività',
    profile: 'Profilo',
    logout: 'Esci',
    changePassword: 'Cambia Password',
    welcome: 'Benvenuto',
    yourTasks: 'Le tue attività',
    noTasks: 'Nessuna attività ancora',
    addNewTask: 'Aggiungi Nuova Attività',
    editTask: 'Modifica Attività',
    title: 'Titolo',
    description: 'Descrizione',
    dueDate: 'Data di scadenza',
    priority: 'Priorità',
    course: 'Corso',
    low: 'Bassa',
    medium: 'Media',
    high: 'Alta',
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    complete: 'Completa',
    settings: 'Impostazioni',
    language: 'Lingua',
    aiAssistant: 'Assistente Studio AI',
    connectMicrosoft: 'Accedi con Microsoft',
    syncNow: 'Sincronizza Ora',
    connected: 'Connesso',
    disconnected: 'Disconnesso',
  },
  tr: {
    dashboard: 'Panel',
    tasks: 'Görevler',
    weekly: 'Haftalık',
    today: 'Bugün',
    emailSync: 'E-posta Senkronizasyonu',
    addTask: '+ Görev Ekle',
    profile: 'Profil',
    logout: 'Çıkış Yap',
    changePassword: 'Parola Değiştir',
    welcome: 'Hoş geldiniz',
    yourTasks: 'Görevleriniz',
    noTasks: 'Henüz görev yok',
    addNewTask: 'Yeni Görev Ekle',
    editTask: 'Görevi Düzenle',
    title: 'Başlık',
    description: 'Açıklama',
    dueDate: 'Bitiş Tarihi',
    priority: 'Öncelik',
    course: 'Ders',
    low: 'Düşük',
    medium: 'Orta',
    high: 'Yüksek',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    complete: 'Tamamla',
    settings: 'Ayarlar',
    language: 'Dil',
    aiAssistant: 'AI Çalışma Asistanı',
    connectMicrosoft: 'Microsoft ile giriş yap',
    syncNow: 'Şimdi Senkronize Et',
    connected: 'Bağlı',
    disconnected: 'Bağlı değil',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    const rtlLanguages = ['ar', 'he', 'fa', 'ur'];
    document.documentElement.dir = rtlLanguages.includes(language) ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
];
